=== S-YOU/trace-samples/opt_ffs/schema/config3.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>FFS version 2.0 schema</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="FFS">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Logging" type="Logging_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Repository" type="Repository_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Plugin" type="Plugin_Type" minOccurs="1" maxOccurs="unbounded" />
				<xsd:element name="Models" type="Models_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="TrafficModel" type="TrafficModel_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Analyzer" type="Analyzer_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
		
   		<xsd:unique name="Model_DefUniqueName">
			<xsd:selector xpath="Models/Model"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
   		</xsd:unique>
	</xsd:element>
	
	<xsd:complexType name="Logging_Type">
		<xsd:attribute name="path" />
		<xsd:attribute name="snapshotTime" />
		<xsd:attribute name="snapshotInConsole"/>
		<xsd:attribute name="statistics" />
		<xsd:attribute name="logDataInOut" />
		<xsd:attribute name="debugLogging" />
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type">
		<xsd:sequence>
			<xsd:element name="Global" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
			<xsd:element name="Local" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type_Scope">
		<xsd:sequence>
			<xsd:element name="Variable" type="Variable_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="import" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Variable_Type">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Fixed"/>
					<xsd:enumeration value="Step"/>
					<xsd:enumeration value="RandomRange"/>
					<xsd:enumeration value="Date"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		
		<xsd:attribute name="start" use="optional" />
		<xsd:attribute name="stepsize" use="optional" />
		<xsd:attribute name="max" use="optional" />

		<xsd:attribute name="to" use="optional" />
		<xsd:attribute name="from" use="optional" />

		<xsd:attribute name="format" use="optional" />
		<xsd:attribute name="parseformat" use="optional" />
		<xsd:attribute name="timezone" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Plugin_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Analyzer_Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Models_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="Model_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Model_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Group" type="Group_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="logLevel" />
	</xsd:complexType>
	
	<xsd:complexType name="Group_Type">
		<xsd:sequence>
	        <xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Item_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Data" type="Data_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Assert" type="Assert_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Out" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="delay">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" default="out_sync">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="out_sync"/>
					<xsd:enumeration value="out_async"/>
					<xsd:enumeration value="wait"/>
					<xsd:enumeration value="pause"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_request" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_condition" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
					<xsd:maxInclusive value="63"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="timeout" use="optional" default="100">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="waitPrepare" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="plugin" use="optional" />
		<xsd:attribute name="expectedResult" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="prevCondition" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Data_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Assert_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"></xsd:any>
        </xsd:sequence>
        <xsd:attribute name="expected" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="mapkey" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="TrafficModel_Type">
		<xsd:sequence>
			<xsd:element name="Slot" type="Slot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="ModelSlot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="times" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="duration" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="tps" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="activeModels" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="ModelSlot_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="weight">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="100"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Script_Type" mixed="true">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
		<xsd:attribute name="engineName"/>
	</xsd:complexType>
</xsd:schema>

=== S-YOU/trace-samples/var_ffs/usecases_old/sms/cipip_sms.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="2000" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="AcctAppID" type="Fixed" value="0" datatype="Long" />
			<Variable name="AuthAppID" type="Fixed" value="16777232" datatype="Long" />
			<Variable name="Subscription-Id-IMSI" type="Fixed" value="262471115009020" datatype="Long" />
			<Variable name="destIP" type="Fixed" value="sdphostname.domain" datatype="String" />
			<Variable name="destPort" type="Fixed" value="8732" datatype="String" />
			<Variable name="destRealm" type="Fixed" value="domain" datatype="String" />
			<Variable name="destVendorID" type="Fixed" value="193" datatype="Long" />
			<Variable name="ownIP" type="Fixed" value="simulatorhostname.domain" datatype="String" />
			<Variable name="ownPort" type="RandomRange" from="8732" to="9000" datatype="String" />
			<Variable name="ownRealm" type="Fixed" value="domain" datatype="String" />
			<Variable name="ownVendorID" type="Fixed" value="193" datatype="Long" />
			<Variable name="randomRange" type="RandomRange" from="70500192" to="70500192" datatype="Long" />
			<Variable name="recordNumber" type="Fixed" value="0" datatype="Long" />
			<!-- DATA Variable name="serviceContextID" type="Fixed" value="6.32251@3gpp.org" datatype="String" /-->
			<Variable name="serviceContextID" type="Fixed" value="Core_Context_R1A@ericsson.com" datatype="String" />
			<Variable name="randomSession" type="RandomRange" from="0000" to="9999" datatype="Long" />
			<Variable name="nowunix" type="Date" format="UNIX" timezone="" value="" datatype="String" />
			<!--Variable name="sessionID" type="Fixed" value="ffs-8-971698181-05f0ea39" datatype="String" /-->
			<Variable name="sessionID" type="Fixed" value="ffs-${Global.nowunix}-${Global.randomSession}" datatype="String" />
			<Variable name="step" type="Step" start="0" stepsize="1" datatype="Long" />
			<Variable name="subCons" type="Fixed" value="389" datatype="String" />
			<Variable name="nowin" type="Date" format="yy-MM-dd HH:mm:ss.SSS z" timezone="GMT+1" value="" datatype="String" />
			<Variable name="then" type="Date" format="NTP" timezone="GMT+1" value="" datatype="String" />
			<Variable name="A-Number" type="Fixed" value="4647000000" datatype="String" />
			<Variable name="B-Number" type="Fixed" value="47000000" datatype="String" />
		</Global>
		<Local>
			<Variable name="recordNumber" type="Fixed" value="0" datatype="Long" />
			<Variable name="reqNum" type="Step" start="0" stepsize="1" datatype="Long" />
			<Variable name="session" type="Fixed" value="nothing" datatype="String" />
			<Variable name="subID" type="Fixed" value="nothing" datatype="String" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.diameter.Diameter">
		<Argument name="ownRealm" value="${Global.ownRealm}" />
		<Argument name="serviceContextID" value="${Global.serviceContextID}" />
		<Argument name="destURI" value="aaa://${Global.destIP}:${Global.destPort};transport=sctp" />
		<Argument name="dictionaryPath" value="config/diameter/dictionary.xml" />
		<Argument name="destRealm" value="${Global.destRealm}" />
		<Argument name="ownProductID" value="CCN" />
		<Argument name="waitForCEATimeout" value="15000" />
		<Argument name="ownVendorID" value="${Global.ownVendorID}" />
		<Argument name="destVendorID" value="${Global.destVendorID}" />
		<Argument name="AcctAppID" value="${Global.AcctAppID}" />
		<Argument name="ownURI" value="aaa://${Global.ownIP}:${Global.ownPort};transport=tcp" />
		<Argument name="AuthAppID" value="${Global.AuthAppID}" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="1000" timeout="30000" type="out_sync">
				<Data name="RequestType" value="CIR" datatype="String" />
				<Data name="DiameterRequest" value="/var/opt/ffs/usecases/sms/cipip_sms_request_01.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
			<Item repeat="1" delay="1000" timeout="30000" parent_request="1" parent_condition="1" type="out_sync">
				<Data name="RequestType" value="CIR" datatype="String" />
				<Data name="DiameterRequest" value="/var/opt/ffs/usecases/sms/cipip_sms_request_02.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/test/prevConditionTest.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="2000" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>

		</Global>
		<Local>

		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.dummyplugin.DummyPlugin">
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M2">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="returnType" value="0" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="returnType" value="1" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync" prevCondition="ok" >
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<!-- 61200000 17h :), 57600000 16h -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M2" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/cdr/base/cs_base.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="5000" snapshotInConsole="true" statistics="false" logDataInOut="fine" debugLogging="fine" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="DestinationType" type="Fixed" value="File" datatype="String" />
		</Global>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.cdr.Cdr">
        <Argument name="cdrFilePrintedAfterCreation" value="YES" /> <!-- YES/NO -->
        <Argument name="cdrFileTargetFolder" value="" />
        <Argument name="cdrFileNameNodeID" value="FFS" />
        <Argument name="cdrFileNamePrivateInformation" value="FFSGenerated" />
        <Argument name="cdrFileNameExtension" value="cdr" />
        <Argument name="cdrMaxFileSize" value="1000000" />
        <Argument name="cdrFileMaxNumberOfRecordsPerFile" value="100000" />
        <Argument name="cdrFileIncludeHeader" value="YES" /> <!-- YES/NO, flag for both record and file header-->
        
        <!-- Valid NAI values: NAI_UNKNOWN, NAI_INTERNATIONAL_NUMBER, NAI_NATIONAL_SIGNIFICANT_NUMBER, NAI_NETWORK_SPECIFIC_NUMBER,
         NAI_SUBSCRIBER_NUMBER, NAI_RESERVED, NAI_ABBREVIATED_NUMBER, NAI_RESERVED_FOR_EXTENSION -->
        
        <!-- Valid NPI values: NPI_UNKNOWN, NPI_ISDN, NPI_SPARE_ONE, NPI_DATA_NUMBERING, NPI_TELEX, NPI_SPARE_TWO, NPI_LAND_MOBILE,
         NPI_SPARE_THREE, NPI_NATIONAL_NUMBERING, NPI_PRIVATE_NUMBERING -->
        
        <!--MSISDN -->
        <Argument name="servedMSISDNprefix" value="46" />  
        <Argument name="servedMSISDNStartValue" value="10" /> 
        <Argument name="servedMSISDNStopValue"   value="100" />
        <Argument name="servedMSISDNRandomNumberInRange" value="NO" /> <!-- YES/NO, YES=Random, NO=Sequence -->
        <Argument name="servedMSISDNnai" value="NAI_INTERNATIONAL_NUMBER"/>
        <Argument name="servedMSISDNnpi" value="NPI_ISDN" />
        <!-- END MSISDN -->
        
        <!-- IMSI -->
        <Argument name="servedIMSIStartValue" value="100000" />
        <Argument name="servedIMSIStopValue" value="200000" />
        <Argument name="servedIMSIRandomNumberInRange" value="NO" /> <!-- YES/NO, YES=Random, NO=Sequence -->
        <!-- END IMSI -->
        
        <!-- CalledNumber -->
        <Argument name="calledNumberprefix" value="46" />  
        <Argument name="calledNumberStartValue" value="60" /> 
        <Argument name="calledNumberStopValue"   value="600" />
        <Argument name="calledNumberRandomNumberInRange" value="NO" /> <!-- YES/NO, YES=Random, NO=Sequence -->
        <Argument name="calledNumbernai" value="NAI_INTERNATIONAL_NUMBER"/>
        <Argument name="calledNumbernpi" value="NPI_ISDN" />
        <!-- END CalledNumber -->
        
        <!-- CallingNumber -->
        <Argument name="callingNumberprefix" value="46" />  
        <Argument name="callingNumberStartValue" value="50" /> 
        <Argument name="callingNumberStopValue"   value="500" />
        <Argument name="callingNumberRandomNumberInRange" value="NO" /> <!-- YES/NO, YES=Random, NO=Sequence -->
        <Argument name="callingNumbernai" value="NAI_INTERNATIONAL_NUMBER"/>
        <Argument name="callingNumbernpi" value="NPI_ISDN" />
        <!-- END CallingNumber -->
        
        <Argument name="callReferenceNumberStartValue" value="10" />
        <Argument name="callReferenceNumberStopValue" value="100" />
       
        <Argument name="releaseTime" value="20141203121314+0100"/>
        <Argument name="answerTime" value="now" />
        <Argument name="originationTime" value="now" />
        <Argument name="deliveryTime" value="now" />
  	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="MOCallRecord">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="Asn1Choice" value="CSRecord" datatype="String" />

                <!-- Values: MOCALLRECORD = 1, MTCALLRECORD = 2, MOSMSRECORD = 3, MTSMSRECORD = 4 -->
                <Data name="Asn1ChoiceType" value="1" datatype="String" />

                <Data name="Asn1Type" value="MOCallRecord" datatype="String" />
				<Data name="CDRRequest" value="./cs_domain_mocallrecord.xml" datatype="FileContent" />
			</Item>
        </Model>
        <Model name="MTCallRecord">
            <Item repeat="1" delay="0" timeout="30000" type="out_sync">
                <Data name="Asn1Choice" value="CSRecord" datatype="String" />

                <!-- Values: MOCALLRECORD = 1, MTCALLRECORD = 2, MOSMSRECORD = 3, MTSMSRECORD = 4 -->
                <Data name="Asn1ChoiceType" value="2" datatype="String" />

                <Data name="Asn1Type" value="MTCallRecord" datatype="String" />
                <Data name="CDRRequest" value="./cs_domain_mtcallrecord.xml" datatype="FileContent" />
            </Item>
        </Model>
        <Model name="MOSMSRecord">
            <Item repeat="1" delay="0" timeout="30000" type="out_sync">
                <Data name="Asn1Choice" value="CSRecord" datatype="String" />

                <!--  Values: MOCALLRECORD = 1, MTCALLRECORD = 2, MOSMSRECORD = 3, MTSMSRECORD = 4  -->
                <Data name="Asn1ChoiceType" value="3" datatype="String" />

                <Data name="Asn1Type" value="MOSMSRecord" datatype="String" />
                <Data name="CDRRequest" value="./cs_domain_mosmsrecord.xml" datatype="FileContent" />
            </Item>
        </Model>
        <Model name="MTSMSRecord">
            <Item repeat="1" delay="0" timeout="30000" type="out_sync">
                <Data name="Asn1Choice" value="CSRecord" datatype="String" />

                <!-- Values: MOCALLRECORD = 1, MTCALLRECORD = 2, MOSMSRECORD = 3, MTSMSRECORD = 4 -->
                <Data name="Asn1ChoiceType" value="4" datatype="String" />

                <Data name="Asn1Type" value="MTSMSRecord" datatype="String" />
                <Data name="CDRRequest" value="./cs_domain_mtsmsrecord.xml" datatype="FileContent" />
            </Item>
        </Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="5" duration="0" tps="0" activeModels="0">
			<Model name="MOCallRecord" weight="100" />
		</Slot>
        <Slot times="5" duration="0" tps="0" activeModels="0">
            <Model name="MTCallRecord" weight="100" />
        </Slot>
        <Slot times="5" duration="0" tps="0" activeModels="0">
            <Model name="MOSMSRecord" weight="100" />
        </Slot>
        <Slot times="5" duration="0" tps="0" activeModels="0">
            <Model name="MTSMSRecord" weight="100" />
        </Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/report/report.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="5000" snapshotInConsole="true" statistics="true" logDataInOut="false" debugLogging="false" />

	<!-- Repository section -->
	<Repository>
	</Repository>

	<!--Report plug-in  -->
	<Plugin class="cmg.tools.ffs.plugins.report.Report" name="Report plugin"> 
		<!-- Mandatory plugin arguments -->
		<Argument name="report.settings" value="report_settings.xml" />
		<!--Optional -->
		<Argument name="report.label" value="12h_performance" />
	</Plugin>
	
		
	<!-- Default simulator plug-in, which send the request defined in the Model and TrafficModel section -->
	<Plugin class="">
		<!-- Mandatory plugin arguments -->
		<Argument name="" value="" />
	</Plugin>
	
	
	<!-- Models section -->
	<Models>
	</Models>
	 
	<TrafficModel>	
	</TrafficModel>
	
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/test/migrate_v3.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="false" statistics="false" logDataInOut="false" debugLogging="false" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="aIncreasingValue" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="sleep" type="Fixed" value="100" datatype="Long" />
		</Global>
		<Local>
			<Variable name="aIncreasingValue" type="Step" start="0" stepsize="1" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.dummyplugin.DummyPlugin">
		<Argument name="arg3" value="${Global.aIncreasingValue}" />
		<Argument name="arg2" value="${Global.sleep}" />
		<Argument name="arg1" value="Value_1_On_Argument" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="sleep" value="${Global.sleep}" datatype="Long" />
				<Data name="sessionId" value="${Local.aIncreasingValue}" datatype="Integer" />
				<Data name="z" value="${Global.aIncreasingValue}" datatype="Integer" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="10" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/mobilemoney/provisioning_admin.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<!-- This must be an Integer so cannot start with 0 (will be removed), add 0 in the model instead. -->
			<Variable name="aIncreasingValue" type="Step" start="709926820" stepsize="1" datatype="Integer" />
			<Variable name="destIP" type="Fixed" value="127.0.0.1" datatype="String" />
			<Variable name="destPort" type="Fixed" value="1077" datatype="String" />
		</Global>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.mobilemoney.ProvisioningAdmin">
		<Argument name="port" value="${Global.destPort}" />
		<Argument name="host" value="${Global.destIP}" />
		<Argument name="threads" value="100" /> <!-- Should be equal to the number of threads FFS uses concurrently -->
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="300" type="out_sync">
				<Data name="doActivation" value="true" datatype="String" />		 	<!-- optional, defaults to false -->
				<Data name="externalId" value="0${Global.aIncreasingValue}" datatype="String" /> <!-- optional, defaults to "46733495865" NOTE: add 0 here if number should start with 0 -->
				<Data name="pinCode" value="111111" datatype="String" />			<!-- optional, defaults to "123456" -->
				<!--<Data name="parent" value="1" datatype="String" /> -->			<!-- optional, parent account holder external id, defaults to "1" -->
				<!--<Data name="profile" value="Mobile Money Agent Profile" datatype="String" /> -->	<!-- optional, defaults to "Mobile Money Agent Profile" -->			
				<!--<Data name="bankId" value="id" datatype="String" />	-->				<!-- optional, defaults to null -->
				<!--<Data name="bankAccount" value="12345678" datatype="String" /> -->	<!-- optional, defaults to null -->

				<!-- THESE PARAMETERS ARE CURRENTLY NOT USED -->
				<!--<Data name="name" value="Svampbob" datatype="String" /> -->				<!-- optional, defaults to "FFS" -->
				<!-- <Data name="surName" value="Fyrkant" datatype="String" /> -->			<!-- optional, defaults to "Default" -->
				<!-- <Data name="idNumber" value="12345678" datatype="String" /> -->			<!-- optional, defaults to "12345678" -->
				<!--<Data name="identificationType" value="Passport" datatype="String" /> -->	<!-- optional, defaults to null -->
				<!--<Data name="homePhoneNumber" value="555123456" datatype="String" />	--><!-- optional, defaults to null -->
				<!--<Data name="email" value="user@mmi.se" datatype="String" />	-->		<!-- optional, defaults to null -->
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="10" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>
