=== S-YOU/trace-samples/opt_ffs/schema/config3.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>FFS version 2.0 schema</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="FFS">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Logging" type="Logging_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Repository" type="Repository_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Plugin" type="Plugin_Type" minOccurs="1" maxOccurs="unbounded" />
				<xsd:element name="Models" type="Models_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="TrafficModel" type="TrafficModel_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Analyzer" type="Analyzer_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
		
   		<xsd:unique name="Model_DefUniqueName">
			<xsd:selector xpath="Models/Model"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
   		</xsd:unique>
	</xsd:element>
	
	<xsd:complexType name="Logging_Type">
		<xsd:attribute name="path" />
		<xsd:attribute name="snapshotTime" />
		<xsd:attribute name="snapshotInConsole"/>
		<xsd:attribute name="statistics" />
		<xsd:attribute name="logDataInOut" />
		<xsd:attribute name="debugLogging" />
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type">
		<xsd:sequence>
			<xsd:element name="Global" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
			<xsd:element name="Local" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type_Scope">
		<xsd:sequence>
			<xsd:element name="Variable" type="Variable_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="import" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Variable_Type">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Fixed"/>
					<xsd:enumeration value="Step"/>
					<xsd:enumeration value="RandomRange"/>
					<xsd:enumeration value="Date"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		
		<xsd:attribute name="start" use="optional" />
		<xsd:attribute name="stepsize" use="optional" />
		<xsd:attribute name="max" use="optional" />

		<xsd:attribute name="to" use="optional" />
		<xsd:attribute name="from" use="optional" />

		<xsd:attribute name="format" use="optional" />
		<xsd:attribute name="parseformat" use="optional" />
		<xsd:attribute name="timezone" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Plugin_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Analyzer_Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Models_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="Model_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Model_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Group" type="Group_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="logLevel" />
	</xsd:complexType>
	
	<xsd:complexType name="Group_Type">
		<xsd:sequence>
	        <xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Item_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Data" type="Data_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Assert" type="Assert_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Out" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="delay">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" default="out_sync">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="out_sync"/>
					<xsd:enumeration value="out_async"/>
					<xsd:enumeration value="wait"/>
					<xsd:enumeration value="pause"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_request" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_condition" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
					<xsd:maxInclusive value="63"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="timeout" use="optional" default="100">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="waitPrepare" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="plugin" use="optional" />
		<xsd:attribute name="expectedResult" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="prevCondition" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Data_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Assert_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"></xsd:any>
        </xsd:sequence>
        <xsd:attribute name="expected" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="mapkey" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="TrafficModel_Type">
		<xsd:sequence>
			<xsd:element name="Slot" type="Slot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="ModelSlot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="times" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="duration" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="tps" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="activeModels" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="ModelSlot_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="weight">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="100"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Script_Type" mixed="true">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
		<xsd:attribute name="engineName"/>
	</xsd:complexType>
</xsd:schema>

=== S-YOU/trace-samples/opt_ffs/config/test/scriptTest.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="2000" snapshotInConsole="true" statistics="false" logDataInOut="finest" debugLogging="600" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="gCount" type="Step" start="0" stepsize="1" datatype="Integer" />
		</Global>
		<Local>
			<Variable name="lCount" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="lFixed" type="Fixed" value="${gCount}" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.dummyplugin.DummyPlugin">
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M2" logLevel="finest">
			<Script>
				function log(msg) {
					_this.log(msg);
				};
			</Script>
			<Group repeat="2">
				<Item repeat="1" delay="1000" timeout="30000" type="out_sync">
					<Data name="log" value="${lFixed}, Item 1" datatype="String" />
				</Item>
				<Script engineName="JavaScript">
					log("tjo");
				</Script>
			</Group>
			<Script>
				log(lFixed+", lCount "+lCount.get()+ " hash: "+lCount.moduleHash());
				log(lFixed+", local_lCount "+local_lCount);
				log(lFixed+", gCount "+gCount.getCurrent());
				lCount.set(5);
			</Script>
			<Item repeat="1" delay="1000" timeout="30000" type="out_sync">
				<Data name="log" value="${lFixed}, Item 4 c${lCount}" datatype="String" />
			</Item>
			<Script>
				if(lCount.getCurrent() != 6)
				{
					log(lFixed+", lCount "+lCount.getCurrent()+ " hash: "+lCount.moduleHash());
					_this.result.markAsFailed();
				}
				else
				{
					log(lFixed+", lCount ok hash: "+lCount.moduleHash());
				}
			</Script>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<!-- 61200000 17h :), 57600000 16h -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M2" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/diameter/str/str.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="false" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="AcctAppID" type="Fixed" value="3" datatype="Integer" />
			<Variable name="AuthAppID" type="Fixed" value="0" datatype="Integer" />
			<Variable name="aIncreasingValue" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="destIP" type="Fixed" value="127.0.0.1" datatype="String" />
			<Variable name="destPort" type="Fixed" value="3868" datatype="String" />
			<Variable name="destRealm" type="Fixed" value="ericsson.com" datatype="String" />
			<Variable name="destVendorID" type="Fixed" value="0" datatype="Integer" />
			<Variable name="ownIP" type="Fixed" value="127.0.0.1" datatype="String" />
			<Variable name="ownPort" type="Fixed" value="9999" datatype="String" />
			<Variable name="ownRealm" type="Fixed" value="client.com" datatype="String" />
			<Variable name="ownVendorID" type="Fixed" value="0" datatype="Integer" />
		</Global>
		<Local>
			<Variable name="recordNumber" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="sessionID" type="Fixed" value="nothing" datatype="String" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.diameter.Diameter">
		<Argument name="ownRealm" value="${Global.ownRealm}" />
		<Argument name="destURI" value="aaa://${Global.destIP}:${Global.destPort};transport=tcp" />
		<Argument name="dictionaryPath" value="config/diameter/dictionary.xml" />
		<Argument name="destRealm" value="${Global.destRealm}" />
		<Argument name="ownProductID" value="MultiMediation" />
		<Argument name="waitForCEATimeout" value="15000" />
		<Argument name="ownVendorID" value="${Global.ownVendorID}" />
		<Argument name="destVendorID" value="${Global.destVendorID}" />
		<Argument name="AcctAppID" value="${Global.AcctAppID}" />
		<Argument name="ownURI" value="aaa://${Global.ownIP}:${Global.ownPort};transport=tcp" />
		<Argument name="AuthAppID" value="${Global.AuthAppID}" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="RequestType" value="ACR" datatype="String" />
				<Data name="DiameterRequest" value="./str_start.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" parent_request="1" parent_condition="1" type="out_sync">
				<Data name="RequestType" value="STR" datatype="String" />
				<Data name="DiameterRequest" value="./str_str.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" parent_request="1" parent_condition="1" type="out_sync">
				<Data name="RequestType" value="ACR" datatype="String" />
				<Data name="DiameterRequest" value="./str_event.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" parent_request="1" parent_condition="1" type="out_sync">
				<Data name="RequestType" value="ACR" datatype="String" />
				<Data name="DiameterRequest" value="config/diameter/str/str_stop.xml" datatype="XMLDocument" />
				<Data name="PBit" value="true" datatype="String" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/test/groupTest.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="2000" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="gCount" type="Step" start="0" stepsize="1" datatype="Integer" />
		</Global>
		<Local>
			<Variable name="lCount" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="lFixed" type="Fixed" value="${gCount}" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.dummyplugin.DummyPlugin">
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M2">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="log" value="Item 0, f${lFixed} c${lCount}" datatype="String" />
			</Item>
			<Group repeat="2">
				<Item repeat="3" delay="0" timeout="30000" type="out_sync">
					<Data name="log" value="  Item 1, Grouped, f${lFixed} c${lCount}" datatype="String" />
				</Item>
				<Item repeat="1" delay="0" timeout="30000" type="out_sync">
					<Data name="log" value="  Item 2, Grouped, f${lFixed} c${lCount}" datatype="String" />
				</Item>
			</Group>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="log" value="Item 3, f${lFixed} c${lCount}" datatype="String" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M2" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/cdr/base/ps_base.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="5000" snapshotInConsole="true" statistics="false" logDataInOut="finest" debugLogging="finest" />


	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="DestinationType" type="Fixed" value="File" datatype="String" />
		</Global>
		<Local>
			<!--   <Variable name="recordNumber" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="sessionID" type="Fixed" value="${sessionConst};${rnd};${now};${step}" datatype="String" />
            -->
            <Variable name="servedMSISDN" type="Step" start="1414001000" stepsize="1" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.cdr.Cdr">
        <Argument name="cdrFileNameNodeID" value="FFS1" />
        <Argument name="cdrFileNamePrivateInformation" value="cdrGeneratedByFFS" />
        <Argument name="cdrFileNameExtension" value="bx" />
        <Argument name="cdrMaxFileSize" value="1000000" />
        <Argument name="cdrFileMaxNumberOfRecordsPerFile" value="10000" />

        <Argument name="recordOpeningTime" value="20141203121314+0100"/>
        <Argument name="startTime" value="now" />
        <Argument name="stopTime" value="now" />
        <Argument name="eventTimeStamp" value="now" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="SGSNSMORecord">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="Asn1Choice" value="GPRSRecord" datatype="String" />

                <!-- "Values: SGSNSMORECORD = 1, SGSNSMTRECORD = 2, PGWRECORD = 3 -->
                <Data name="Asn1ChoiceType" value="1" datatype="String" />

                <Data name="Asn1Type" value="SGSNSMORecord" datatype="String" />
				<Data name="CDRRequest" value="./ps_domain_sgsnmorecord.xml" datatype="FileContent" />
			</Item>
	   </Model>
       <Model name="SGSNSMTRecord">
            <Item repeat="1" delay="0" timeout="30000" type="out_sync">
                <Data name="Asn1Choice" value="GPRSRecord" datatype="String" />

                <!-- "Values: SGSNSMORECORD = 1, SGSNSMTRECORD = 2, PGWRECORD = 3 -->
                <Data name="Asn1ChoiceType" value="2" datatype="String" />

                <Data name="Asn1Type" value="SGSNSMTRecord" datatype="String" />
                <Data name="CDRRequest" value="./ps_domain_sgsnmtrecord.xml" datatype="FileContent" />
            </Item>
       </Model>
       <Model name="PGWRecord">
            <Item repeat="1" delay="0" timeout="30000" type="out_sync">
                <Data name="Asn1Choice" value="GPRSRecord" datatype="String" />

                <!-- "Values: SGSNSMORECORD = 1, SGSNSMTRECORD = 2, PGWRECORD = 3 -->
                <Data name="Asn1ChoiceType" value="3" datatype="String" />

                <Data name="Asn1Type" value="PGWRecord" datatype="String" />
                <Data name="CDRRequest" value="./ps_domain_pgwrecord.xml" datatype="FileContent" />
            </Item>
       </Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
    	<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="SGSNSMORecord" weight="100" />
		</Slot>
        <Slot times="1" duration="0" tps="0" activeModels="0">
            <Model name="SGSNSMTRecord" weight="100" />
        </Slot>
        <Slot times="1" duration="0" tps="0" activeModels="0">
            <Model name="PGWRecord" weight="100" />
        </Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/webservices/config_onlinegeneral.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="false" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="destIP" type="Fixed" value="136.225.18.12" datatype="String" />
			<Variable name="destPort" type="Fixed" value="1090" datatype="String" />
		</Global>
		<Local>
			<Variable name="securiy_context_token" type="Fixed" value="null" datatype="String" /> 
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.http.HTTP">
		<Argument name="port" value="${Global.destPort}" />
		<Argument name="maxTotalConnections" value="20" />
		<Argument name="host" value="${Global.destIP}" />
		<Argument name="maxConnectionsPerHost" value="2" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="Method" value="POST" datatype="String" />
				<Data name="Content-Type" value="text/xml;charset=utf-8" datatype="String" />
				<Data name="URI" value="/general/general.ws" datatype="String" />
				<Data name="SOAPAction" value="execute" datatype="String" />
				<Data name="data" value="./content.xml" datatype="FileContent"/>
				<Data name="expected_xml_response" value="//username[1]='user'" datatype="String"/>
				<Out variable="${securiy_context_token}" src="XML_RESPONSE.//Identifier[1]" pattern="" /> 
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/mobilemoney/test-provisioning.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
		</Global>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.mobilemoney.TestProvisioning">
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="300" type="out_sync">
				<Data name="clean" value="true" />
				<Data name="provision" value="vobs\mmon\MMON\util\test-ol-m3\Module_Test\AllTest\reset.xml" datatype="FileContent" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>
