=== S-YOU/trace-samples/opt_ffs/schema/config3.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>FFS version 2.0 schema</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="FFS">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Logging" type="Logging_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Repository" type="Repository_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Plugin" type="Plugin_Type" minOccurs="1" maxOccurs="unbounded" />
				<xsd:element name="Models" type="Models_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="TrafficModel" type="TrafficModel_Type" minOccurs="1" maxOccurs="1" />
				<xsd:element name="Analyzer" type="Analyzer_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
		
   		<xsd:unique name="Model_DefUniqueName">
			<xsd:selector xpath="Models/Model"></xsd:selector>
			<xsd:field xpath="@name"></xsd:field>
   		</xsd:unique>
	</xsd:element>
	
	<xsd:complexType name="Logging_Type">
		<xsd:attribute name="path" />
		<xsd:attribute name="snapshotTime" />
		<xsd:attribute name="snapshotInConsole"/>
		<xsd:attribute name="statistics" />
		<xsd:attribute name="logDataInOut" />
		<xsd:attribute name="debugLogging" />
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type">
		<xsd:sequence>
			<xsd:element name="Global" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
			<xsd:element name="Local" type="Repository_Type_Scope" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Repository_Type_Scope">
		<xsd:sequence>
			<xsd:element name="Variable" type="Variable_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="import" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Variable_Type">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Fixed"/>
					<xsd:enumeration value="Step"/>
					<xsd:enumeration value="RandomRange"/>
					<xsd:enumeration value="Date"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		
		<xsd:attribute name="start" use="optional" />
		<xsd:attribute name="stepsize" use="optional" />
		<xsd:attribute name="max" use="optional" />

		<xsd:attribute name="to" use="optional" />
		<xsd:attribute name="from" use="optional" />

		<xsd:attribute name="format" use="optional" />
		<xsd:attribute name="parseformat" use="optional" />
		<xsd:attribute name="timezone" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Plugin_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" use="optional" />
	</xsd:complexType>
	
	<xsd:complexType name="Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Type">
		<xsd:sequence>
			<xsd:element name="Argument" type="Analyzer_Argument_Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="class" />
		<xsd:attribute name="name" />
	</xsd:complexType>
	
	<xsd:complexType name="Analyzer_Argument_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="value" />
		<xsd:attribute name="datatype" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Models_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="Model_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Model_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Group" type="Group_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" />
		<xsd:attribute name="logLevel" />
	</xsd:complexType>
	
	<xsd:complexType name="Group_Type">
		<xsd:sequence>
	        <xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Item" type="Item_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Script" type="Script_Type" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Item_Type">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="Data" type="Data_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Assert" type="Assert_Type" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Out" minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="repeat">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="delay">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" default="out_sync">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="out_sync"/>
					<xsd:enumeration value="out_async"/>
					<xsd:enumeration value="wait"/>
					<xsd:enumeration value="pause"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_request" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="parent_condition" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
					<xsd:maxInclusive value="63"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="timeout" use="optional" default="100">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="waitPrepare" use="optional" default="0">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="plugin" use="optional" />
		<xsd:attribute name="expectedResult" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="prevCondition" use="optional" default="">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value=""/>
					<xsd:enumeration value="ok"/>
					<xsd:enumeration value="failed"/>
					<xsd:enumeration value="exception"/>
					<xsd:enumeration value="timeout"/>
					<xsd:enumeration value="other"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Data_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Assert_Type">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"></xsd:any>
        </xsd:sequence>
        <xsd:attribute name="expected" type="xsd:string" />
		<xsd:attribute name="datatype">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"/>
					<xsd:enumeration value="Integer"/>
					<xsd:enumeration value="Double"/>
					<xsd:enumeration value="Long"/>
					<xsd:enumeration value="FileContent"/>
					<xsd:enumeration value="XMLDocument"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="mapkey" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="TrafficModel_Type">
		<xsd:sequence>
			<xsd:element name="Slot" type="Slot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot_Type">
		<xsd:sequence>
			<xsd:element name="Model" type="ModelSlot_Type" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="times" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="duration" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="tps" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="activeModels" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="ModelSlot_Type">
		<xsd:attribute name="name" />
		<xsd:attribute name="weight">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="100"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Script_Type" mixed="true">
        <xsd:sequence>
        	<xsd:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xsd:sequence>
		<xsd:attribute name="engineName"/>
	</xsd:complexType>
</xsd:schema>

=== S-YOU/trace-samples/opt_ffs/config/test/repostest.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="false" statistics="false" logDataInOut="false" debugLogging="false" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="aIncreasingValue" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="tjo" type="Fixed" value="tjo" datatype="String" />
			<Variable name="requestIdCounter" type="Step" start="100" stepsize="1" datatype="Integer" />
			<Variable name="globalSessionCounter" type="Step" start="10000" stepsize="1" datatype="Integer" />
		</Global>
		<Local>
			<Variable name="recordNumber" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="sessionID" type="Fixed" value="not set" datatype="String" />
			<Variable name="hej" type="Fixed" value="hej" datatype="String" />
			<Variable name="local" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="step" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="localSessionCounter" type="Step" start="0" stepsize="1" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.dummyplugin.DummyPlugin">
		<Argument name="arg1" value="Value_1_On_Argument" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="m1.1: session: ${Local.sessionID}.set(${Global.aIncreasingValue})" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="m1.2: session: ${Local.sessionID}, local1: ${Local.local} | ${Global.tjo} ${Local.hej}" datatype="String" />
			</Item>
		</Model>
		<Model name="M2">
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="m2.1: session: ${Local.sessionID}.set(${Global.aIncreasingValue}), local2: ${Local.local}" datatype="String" />
			</Item>
			<Item repeat="9" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="m2.1: session: ${Local.sessionID}, local2: ${Local.local}" datatype="String" />
			</Item>
		</Model>
		<Model name="M3">
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="noop1" value="${Local.sessionID}.set(${Global.aIncreasingValue})" datatype="String" />
				<Data name="print" value="m3.1: session: ${Local.sessionID}" datatype="String" />
			</Item>
		</Model>
		<Model name="M4-xmltest">
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="localstep: ${Local.step}" datatype="String" />
				<Data name="dumpxml" value="config/test/repostest-externalxml.xml" datatype="XMLDocument" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000000" type="out_sync">
				<Data name="print" value="localstep: ${Local.step}" datatype="String" />
				<Data name="dumpxml" value="config/test/repostest-externalxml-dontstep.xml" datatype="XMLDocument" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section 86400000 24h, 10800000 3h -->
	<TrafficModel>
		<Slot times="5" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M2" weight="100" />
		</Slot>
		<Slot times="5" duration="0" tps="0" activeModels="0">
			<Model name="M3" weight="100" />
		</Slot>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M4-xmltest" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>
<!--
The output should look close to this:

Dummy (1) print: m1.1: session: 0
Dummy (2) print: m1.1: session: 1
Dummy (3) print: m1.1: session: 2
Dummy (4) print: m1.1: session: 3
Dummy (5) print: m1.1: session: 4
Dummy (6) print: m2.1: session: 5, local2: 0
Dummy (7) print: m3.1: session: 6
Dummy (8) print: m3.1: session: 7
Dummy (9) print: m3.1: session: 8
Dummy (10) print: m3.1: session: 9
Dummy (11) print: m3.1: session: 10
Dummy (12) print: localstep: 0
Dummy (12) dumpxml: &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/iaccParameters.xsd">
	<Subscriber requestId="100">	
 	   	<Parameter level="0" name="localStep" value="1" valueType="PARAMETER_STRING"/>
  		<Parameter level="0" name="sessionStep" value="10000" valueType="PARAMETER_STRING"/>
	</Subscriber>	
</RequestData>&lt;!- - Stepping external repos - -&gt;
Dummy (1) print: m1.2: session: 0, local1: 0 | tjo hej
Dummy (2) print: m1.2: session: 1, local1: 0 | tjo hej
Dummy (3) print: m1.2: session: 2, local1: 0 | tjo hej
Dummy (4) print: m1.2: session: 3, local1: 0 | tjo hej
Dummy (5) print: m1.2: session: 4, local1: 0 | tjo hej
Dummy (6) print: m2.1: session: 5, local2: 1
Dummy (12) print: localstep: 2
Dummy (12) dumpxml: &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/iaccParameters.xsd">
	<Subscriber requestId="101">	
 	   	<Parameter level="0" name="localStep" value="3" valueType="PARAMETER_STRING"/>
  		<Parameter level="0" name="session" value="10001" valueType="PARAMETER_STRING"/>
 	   	<Parameter level="0" name="hej" value="hej" valueType="PARAMETER_STRING"/>
	</Subscriber>	
</RequestData>&lt;!- - None Stepping external repos - -&gt;
Dummy (6) print: m2.1: session: 5, local2: 2
Dummy (6) print: m2.1: session: 5, local2: 3
Dummy (6) print: m2.1: session: 5, local2: 4
Dummy (6) print: m2.1: session: 5, local2: 5
Dummy (6) print: m2.1: session: 5, local2: 6
Dummy (6) print: m2.1: session: 5, local2: 7
Dummy (6) print: m2.1: session: 5, local2: 8
Dummy (6) print: m2.1: session: 5, local2: 9
-->

=== S-YOU/trace-samples/opt_ffs/config/http/config_parlayx.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="0" snapshotInConsole="false" statistics="false" logDataInOut="true" debugLogging="true" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="destIP" type="Fixed" value="kmx002" datatype="String" />
			<Variable name="destPort" type="Fixed" value="8081" datatype="String" />
		</Global>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.http.HTTP">
		<Argument name="port" value="${Global.destPort}" />
		<Argument name="maxTotalConnections" value="20" />
		<Argument name="host" value="${Global.destIP}" />
		<Argument name="maxConnectionsPerHost" value="2" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="Method" value="POST" datatype="String" />
				<Data name="Content-type" value="text/xml" datatype="String" />
				<Data name="URI" value="/services/ReserveAmountCharging" datatype="String" />
				<Data name="SOAPAction" value="reserveAmount" datatype="String" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/smsc/sms_generic.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="10000" snapshotInConsole="true" statistics="false" logDataInOut="true" debugLogging="false" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="sender" type="Step" start="100000000" stepsize="1" datatype="Integer" max="100000999"/>
		</Global>
		<Local>
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.mobilemoney.SmscSimulator">
		<!-- Mandatory plugin arguments -->
		<Argument name="target.systemid" value="receiver" /><!-- Online F/E -->
		<Argument name="target.password" value="receiver" />
		<Argument name="callback.systemid" value="callback" /><!-- Online B/E -->
		<Argument name="callback.password" value="callback" />
		<Argument name="bind.timeout" value="6" />
		<Argument name="bind.port" value="1982" />
		<!-- Optional plugin arguments -->
		<Argument name="request.timeout" value="30000" />
		
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="modelA">
			<!-- Cash in -->
			<Item repeat="1" delay="0" timeout="3000" type="out_async">
				<Data name="sender" value="${Global.sender}" datatype="String"/>
				<Data name="shortmessage" value="SMS to send" datatype="String"/>
				<!-- Optional regular expression to match the response message towards -->
				<Data name="expectedresponse" value="regularexpression to look for in response, remove to ignore.*" datatype="String"/>
				
				<!-- The following arguments are optional and can be omitted. These can also be put in plugin section abowe in order to set them for all items. -->
				<Data name="encoding" value="ISO-8859-6" datatype="String" /><!-- Supported encodings are std java plus GSM7BIT see: http://java.sun.com/javase/6/docs/technotes/guides/intl/encoding.doc.html -->
				<Data name="dcs" value="0x22" datatype="String" /><!-- DCS flag to put on message -->
				<Data name="payload" value="-1" datatype="String" /><!-- Use message_payload? -1=auto, 0=no, 1=yes -->
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="modelA" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/parlay/config_parlay.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="2000" snapshotInConsole="true" statistics="false" logDataInOut="false" debugLogging="false" />

	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="destIP" type="Fixed" value="127.0.0.1" datatype="String" />
			<Variable name="destPort" type="Fixed" value="15500" datatype="String" />
			<!--Variable name="serviceNameParlay" type="Fixed" value="IpChargingManager" datatype="String" /-->
			<Variable name="serviceNameParlay" type="Fixed" value="InitialContactName" datatype="String" />
			<Variable name="nameServiceNameParlay" type="Fixed" value="NameService" datatype="String" />
		</Global>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.parlay.Parlay">
		<Argument name="port" value="${Global.destPort}" />
		<Argument name="host" value="${Global.destIP}" />
		<Argument name="serviceName" value="${Global.serviceNameParlay}" />
		<Argument name="NameServiceName" value="${Global.nameServiceNameParlay}" />
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="M1">
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="action" value="createChargingSession" datatype="String" />
				<Data name="address" value="config/parlay/parlayAddress.xml" datatype="XMLDocument" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="action" value="reserveAmountReq" datatype="String" />
				<Data name="applicationDescriptionText" value="A reservation example" datatype="String" />
				<Data name="preferredAmount" value="10.0" datatype="Double" />
				<Data name="preferredCurrency" value="XEU" datatype="String" />
				<Data name="minimumAmount" value="5.0" datatype="Double" />
				<Data name="minimumCurrency" value="XEU" datatype="String" />
				<Data name="chargingParameterSet" value="config/parlay/parlayChargingParameter.xml" datatype="XMLDocument" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="action" value="debitAmountReq" datatype="String" />
				<Data name="applicationDescriptionText" value="A debit amount example" datatype="String" />
				<Data name="amount" value="1.0" datatype="Double" />
				<Data name="currency" value="XEU" datatype="String" />
				<Data name="closeReservation" value="false" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="action" value="getAmountLeft" datatype="String" />
			</Item>
			<Item repeat="1" delay="0" timeout="30000" type="out_sync">
				<Data name="action" value="release" datatype="String" />
			</Item>
		</Model>
	</Models>

	<!-- TrafficModels section -->
	<TrafficModel>
		<Slot times="1" duration="0" tps="0" activeModels="0">
			<Model name="M1" weight="100" />
		</Slot>
	</TrafficModel>
</FFS>

=== S-YOU/trace-samples/opt_ffs/config/cdr/base/mms_base.xml
<?xml version="1.0" ?>
<FFS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/config3.xsd">
	<!-- Logging section -->
	<Logging path="logs/" snapshotTime="5000" snapshotInConsole="true" statistics="false" logDataInOut="finest" debugLogging="finest" />


	<!-- Repository section -->
	<Repository>
		<Global>
			<Variable name="DestinationType" type="Fixed" value="File" datatype="String" />                                                            
		</Global>
		<Local>
			<!--   <Variable name="recordNumber" type="Step" start="0" stepsize="1" datatype="Integer" />
			<Variable name="sessionID" type="Fixed" value="${sessionConst};${rnd};${now};${step}" datatype="String" />
            -->
            <Variable name="servedMSISDN" type="Step" start="1414001000" stepsize="1" datatype="Integer" />
		</Local>
	</Repository>

	<!-- Simulator plug-in section -->
	<Plugin class="cmg.tools.ffs.plugins.cdr.Cdr">
        <Argument name="cdrFileNameNodeID" value="FFS1" />        
        <Argument name="cdrFileNamePrivateInformation" value="cdrGeneratedByFFS" />
        <Argument name="cdrFileNameExtension" value="bx" />
        <Argument name="cdrMaxFileSize" value="1000000" />
        <Argument name="cdrFileMaxNumberOfRecordsPerFile" value="10000" />
        
        <Argument name="submissionTime" value="20141203121314+0100"/>
        <Argument name="recordTimeStamp" value="now" />            

        
	</Plugin>

	<!-- Models section -->
	<Models>
		<Model name="MMO1SRecord">
			<Item repeat="1" delay="0" timeout="3000" type="out_sync">
				<Data name="Asn1Choice" value="MMSRecordType" datatype="String" />
                
                <!-- "Values: MMO1SRECORD = 1, MMR1ARECORD = 2 -->
                <Data name="Asn1ChoiceType" value="1" datatype="String" />  
                
                <Data name="Asn1Type" value="MMO1SRecord" datatype="String" />
				<Data name="CDRRequest" value="./mms_domain_mmo1srecord.xml" datatype="FileContent" />
			</Item>
	   </Model>
       <Model name="MMR1ARecord">
            <Item repeat="1" delay="0" timeout="3000" type="out_sync">
                <Data name="Asn1Choice" value="MMSRecordType" datatype="String" />
                
                <!-- "Values: MMO1SRECORD = 1, MMR1ARECORD = 2 -->
                <Data name="Asn1ChoiceType" value="2" datatype="String" />  
                
                <Data name="Asn1Type" value="MMR1ARecord" datatype="String" />
                <Data name="CDRRequest" value="./mms_domain_mmr1arecord.xml" datatype="FileContent" />
            </Item>
       </Model>
    </Models>

	<!-- TrafficModels section -->
	<TrafficModel>
        <Slot times="1" duration="0" tps="0" activeModels="0">
            <Model name="MMO1SRecord" weight="100" />
        </Slot>
        <Slot times="1" duration="0" tps="0" activeModels="0">
            <Model name="MMR1ARecord" weight="100" />
        </Slot>
    </TrafficModel>
</FFS>
