=== S-YOU/trace-samples/opt_ffs/schema/diameterRequest.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
			Diameter definition schema.
		</xsd:documentation>
	</xsd:annotation>

	<!--ROOT element-->
	<xsd:element name="RequestData">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="AVP" type="AVP_Type" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!--Types-->
	<xsd:complexType name="AVP_Type">
		<xsd:sequence>
			<xsd:element name="AVP" type="AVP_Type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		
		<xsd:attribute name="code" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="optional"/>
		<xsd:attribute name="vendor-id" type="xsd:string" use="optional"/>
		<xsd:attribute name="mandatoryFlag" type="mandatoryFlag_type" use="optional"/>
		<xsd:attribute name="type" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="mandatoryFlag_type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="true|false"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== S-YOU/trace-samples/var_ffs/usecases_old/voice_long/voice-long-cs1-cipip_request_01_CallSetup.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<!--AVP code="263" value="8-1426194950-06020255" vendor-id="0" /-->
	<AVP code="263" value="${Global.sessionID}" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 264 Origin-Host -->
	<!-- AVP Code: 296 Origin-Realm -->
	<!-- FFS adds Origin-Host and Origin-Realm automatically-->
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<!--AVP code="415" value="0" vendor-id="0" /-->
	<AVP code="415" value="${Local.reqNum}" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="1" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001234393437313132323437 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="${Global.A-Number}" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 456 Multiple-Services-Credit-Control -->
	<!-- Grouped data: 000001b540000008 -->
	<AVP code="456" value="" vendor-id="0">
		<!-- AVP Code: 437 Requested-Service-Unit -->
		<AVP code="437" value="" vendor-id="0" />
		<!-- AVP Code: 439 Service-Identifier -->
		<AVP code="439" value="0" vendor-id="0" />
		<!-- AVP Code: 1068 Service-Session-Id -->
		<AVP code="1068" value="1" vendor-id="193" />
		<!-- AVP Code: 1075 Other-Party-Id -->
		<!-- Grouped data: 00000434c0000010000000c100000000 -->
		<AVP code="1075" value="" vendor-id="193">
			<!-- AVP Code: 1076 Default-Handling -->
			<AVP code="1076" value="0" vendor-id="193" />
			<!-- AVP Code: 1077 Other-Party-Id-Data -->
			<AVP code="1077" value="${Global.B-Number}" vendor-id="193" />
			<!-- AVP Code: 1078 Other-Party-Id-Type -->
			<AVP code="1078" value="0" vendor-id="193" />
		</AVP>
		<!-- AVP Code: 1121 Roaming-Position -->
		<AVP code="1121" value="0" vendor-id="193" />
		<!-- AVP Code: 1122 Service-Scenario -->
		<AVP code="1122" value="0" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 461 Service-Context-Id -->
	<AVP code="461" value="Core_Context_R1A@ericsson.com" vendor-id="0" />
	<!-- AVP Code: 1063 Access-Information -->
	<!-- Grouped data: 000000374000000cd2dcccbb -->
	<AVP code="1063" value="" vendor-id="193">
		<!-- AVP Code: 55 Event-Timestamp -->
		<!--AVP code="55" value="Feb  8, 2012 11:28:11.000000000" vendor-id="0" /-->
		<AVP code="55" value="${Global.accessTime}" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="CS1plus_V.1.0@ericsson.com" vendor-id="193" />
	<!-- AVP Code: 1074 Subscription-Id-Location -->
	<AVP code="1074" value="4947101002" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 23 3GPP-MS-TimeZone -->
	<AVP code="23" value="0x40:00" vendor-id="10415" />
	<!-- AVP Code: 55 Event-Timestamp -->
	<!--AVP code="55" value="Feb  8, 2012 11:28:11.000000000" vendor-id="0" /-->
	<AVP code="55" value="${Global.accessTime}" vendor-id="0" />
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/str/str_str.xml
<?xml version="1.0" encoding="UTF-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
    <!-- Session-Id -->
	<AVP code="263" value="${Local.sessionID}"></AVP>
    <!-- Destination-Realm -->
    <AVP code="283" value="${Global.destRealm}"></AVP>
    <!-- Destination-Host -->
    <AVP code="293" value="${Global.destIP}"></AVP>
   <!-- Auth-Application-Id -->
      <AVP code="258" value="${Global.AuthAppID}"></AVP>     
     <!-- Vendor-Specific-Application-Id -->
	<AVP code="260" value="">
		<!-- Acct-Application-Id -->
		<AVP code="259" value="${Global.AcctAppID}"></AVP>
		<!-- Auth-Application-Id -->
		<AVP code="258" value="${Global.AuthAppID}"></AVP>
		<!-- Vendor-Id -->
		<AVP code="266" value="${Global.destVendorID}"></AVP>
	</AVP>
	
    <!-- Termination-Cause (Optional) -->
    <!-- <AVP code="295" value="4"/> -->

    <!-- User-Name -->
    <AVP code="1" value="MultiMediation"></AVP>
    <!-- Origin-State-Id (Optional) -->
    <AVP code="278" value="1"></AVP>
    
	<!-- Proxy-Info -->
    <!--<AVP code="284" value="">-->
        <!-- Proxy-State -->
        <!--<AVP code="33" value="1" />-->
        <!-- Proxy-Host -->
        <!--<AVP code="280" value="aaa://127.0.0.1:3868;transport=tcp" />-->
    <!--</AVP>-->


    <!-- Route-Record (Optional) -->
    <!-- <AVP code="282" value="aaa://127.0.0.1:3868;transport=tcp"/> -->


</RequestData>

=== S-YOU/trace-samples/var_ffs/usecases/data/cipip_data_request_06.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<AVP code="263" value="c1-10-99-243-34-ggsn03.ericsson.se;1302790467;88" vendor-id="0" />
	<!-- AVP Code: 30 Called-Station-Id -->
	<AVP code="30" value="67:79:74:73:70:36:30:30:36:2e:6b:61:2e:73:77:2e:65:72:69:63:73:73:6f:6e:2e:73:65" vendor-id="0" />
	<!-- AVP Code: 264 Origin-Host -->
	<AVP code="264" value="tsp6006.ericsson.se" vendor-id="0" />
	<!-- AVP Code: 296 Origin-Realm -->
	<AVP code="296" value="tsp6006.ericsson.se" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="vip17x57.ete.ka.sw.ericsson.se" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<AVP code="415" value="0" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="1" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001234393437313132323435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="4947112245" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc40000017323632343731313030303030303435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="262471100000045" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 461 Service-Context-Id -->
	<AVP code="461" value="6.32251@3gpp.org" vendor-id="0" />
	<!-- AVP Code: 1063 Access-Information -->
	<!-- Grouped data: 000000374000000cd1581021 -->
	<AVP code="1063" value="" vendor-id="193">
		<!-- AVP Code: 55 Event-Timestamp -->
		<AVP code="55" value="3512209441" vendor-id="0" />
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="4" vendor-id="0" />
		<!-- AVP Code: 264 Origin-Host -->
		<AVP code="264" value="c1-10-99-243-34-ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 296 Origin-Realm -->
		<AVP code="296" value="ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 415 CC-Request-Number -->
		<AVP code="415" value="0" vendor-id="0" />
		<!-- AVP Code: 416 CC-Request-Type -->
		<AVP code="416" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="Ericsson_OCS_V1_0.0.0.7.32251@3gpp.org" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 1164 Ericsson-QoS-Profile -->
	<!-- Grouped data: 0000048dc0000010000000c100000003 -->
	<AVP code="1164" value="" vendor-id="193">
		<!-- AVP Code: 1165 Traffic-Class -->
		<AVP code="1165" value="00:00:00:03" vendor-id="193" />
		<!-- AVP Code: 1166 Guaranteed-Bit-Rate-For-Uplink -->
		<AVP code="1166" value="512000" vendor-id="193" />
		<!-- AVP Code: 1168 Guaranteed-Bit-Rate-For-Downlink -->
		<AVP code="1168" value="512000" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 1170 Ericsson-Geographical-Location -->
	<!-- Grouped data: 00000493c0000011000000c13234303939 -->
	<AVP code="1170" value="" vendor-id="193">
		<!-- AVP Code: 1171 Ericsson-Location-MCC-MNC -->
		<AVP code="1171" value="24099" vendor-id="193" />
		<!-- AVP Code: 1172 Ericsson-Location-Area-Code -->
		<AVP code="1172" value="01:d8" vendor-id="193" />
		<!-- AVP Code: 1174 Ericsson-Geo-Location-Cell-Identity -->
		<AVP code="1174" value="00:03" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 2 3GPP-Charging-Id -->
	<AVP code="2" value="" vendor-id="10415" />
	<!-- AVP Code: 3 3GPP-PDP type -->
	<AVP code="3" value="" vendor-id="10415" />
	<!-- AVP Code: 8 3GPP-IMSI MCC-MNC -->
	<AVP code="8" value="" vendor-id="10415" />
	<!-- AVP Code: 10 3GPP-NSAPI -->
	<AVP code="10" value="5" vendor-id="10415" />
	<!-- AVP Code: 12 3GPP-Selection-Mode -->
	<AVP code="12" value="1" vendor-id="10415" />
	<!-- AVP Code: 13 3GPP-Charging-Characteristics -->
	<AVP code="13" value="0000" vendor-id="10415" />
	<!-- AVP Code: 18 3GPP-SGSN MCC-MNC -->
	<AVP code="18" value="" vendor-id="10415" />
	<!-- AVP Code: 21 3GPP-RAT-Type -->
	<AVP code="21" value="00:00:03:e8" vendor-id="10415" />
	<!-- AVP Code: 23 3GPP-MSTimeZone -->
	<AVP code="23" value="80:01" vendor-id="10415" />
	<!-- AVP Code: 847 GGSN-Address -->
	<AVP code="847" value="" vendor-id="10415" />
	<!-- AVP Code: 1227 PDP-Address -->
	<AVP code="1227" value="53.18.0.4" vendor-id="10415" />
	<!-- AVP Code: 1228 SGSN-Address -->
	<AVP code="1228" value="10.99.1.129" vendor-id="10415" />
	<!-- AVP Code: 55 Event-Timestamp -->
	<AVP code="55" value="3512209441" vendor-id="0" />
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/rarasr/RAR.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a sample request template for the ReAuth request. Some of the AVP values provided here are the dummy values.-->
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- Session-Id -->
	<AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" /> 
	 <!-- <AVP code="263" value="1" /> --> 
	<!-- Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" />
	<!-- Destination-Host -->
	<AVP code="293" value="${Global.destIP}" />
	<!-- Auth-Application-Id -->
	<AVP code="258" value="${Global.AuthAppID}" />
	<!-- Re-Auth Request Type -->
	<AVP code="285" value="1" />
	<!-- User-Name -->
	<AVP code="1" value="Mediation" />
 	<!-- Proxy-Info -->
	<AVP code="284" value="" >
		<!-- Proxy-Host -->
		<AVP code="280" value="berarlistener"/>
		<!-- Proxy-State -->
		<AVP code="33" value="running"/>
	</AVP>
	<!-- Route-Record -->
	<AVP code="282" value="berarrouter"/>
	<!-- GSU Pool reference -->
	<AVP code="457" value="" >
		<!-- GSU Pool Identifier -->
		<AVP code="453" value="22" />
		<!-- CC-Unit-Type -->
		<AVP code="454" value="3" />
		<!-- Unit Value -->
		<AVP code="445" value="" >
			<!-- Value Digits -->
			<AVP code="447" value="5" />
			<!-- Exponent -->
			<AVP code="429" value="1" />
		</AVP>
	</AVP>
	<!-- Service Identifier -->
	<AVP code="439" value="berarserviceid"/>
	<!-- Rating Group -->
	<AVP code="432" value="10"/>

</RequestData>

=== S-YOU/trace-samples/opt_ffs/capv2_request_01.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<AVP code="263" value="5-1477982729-093a1858" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 264 Origin-Host -->
	<AVP code="264" value="ccnbl1.intmet.ie" vendor-id="0" />
	<!-- AVP Code: 296 Origin-Realm -->
	<AVP code="296" value="intmet.ie" vendor-id="0" />
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="sdpbl2.intmet.ie" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<AVP code="415" value="0" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="1" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc40000014333533383531313030323331 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="353851100231" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001732373230333031303636313237353700 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="272030106612757" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 456 Multiple-Services-Credit-Control -->
	<!-- Grouped data: 000001b540000008 -->
	<AVP code="456" value="" vendor-id="0">
		<!-- AVP Code: 437 Requested-Service-Unit -->
		<AVP code="437" value="" vendor-id="0" />
		<!-- AVP Code: 439 Service-Identifier -->
		<AVP code="439" value="0" vendor-id="0" />
		<!-- AVP Code: 1068 Service-Session-Id -->
		<AVP code="1068" value="1" vendor-id="193" />
		<!-- AVP Code: 1075 Other-Party-Id -->
		<!-- Grouped data: 00000434c0000010000000c100000000 -->
		<AVP code="1075" value="" vendor-id="193">
			<!-- AVP Code: 1076 Default-Handling -->
			<AVP code="1076" value="0" vendor-id="193" />
			<!-- AVP Code: 1077 Other-Party-Id-Data -->
			<AVP code="1077" value="0852090134" vendor-id="193" />
			<!-- AVP Code: 1078 Other-Party-Id-Type -->
			<AVP code="1078" value="0" vendor-id="193" />
			<!-- AVP Code: 1080 Other-Party-Id-Location -->
			<AVP code="1080" value="35385075431" vendor-id="193" />
			<!-- AVP Code: 1103 Other-Party-Id-MNP -->
			<!-- Grouped data: 00000437c0000011000000c13137363835000000 -->
			<AVP code="1103" value="" vendor-id="193">
				<!-- AVP Code: 1079 Other-Party-Id-MNP-RN -->
				<AVP code="1079" value="17685" vendor-id="193" />
				<!-- AVP Code: 1104 Other-Party-Id-MNP-IMSI -->
				<AVP code="1104" value="272030000000000" vendor-id="193" />
				<!-- AVP Code: 1105 Other-Party-Id-MNP-Result -->
				<AVP code="1105" value="2001" vendor-id="193" />
			</AVP>
		</AVP>
		<!-- AVP Code: 1121 Roaming-Position -->
		<AVP code="1121" value="0" vendor-id="193" />
		<!-- AVP Code: 1122 Service-Scenario -->
		<AVP code="1122" value="2" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 461 Service-Context-Id -->
	<AVP code="461" value="Core_Context_R1A@ericsson.com" vendor-id="0" />
	<!-- AVP Code: 1063 Access-Information -->
	<!-- Grouped data: 000000374000000cd7227f4d -->
	<AVP code="1063" value="" vendor-id="193">
		<!-- AVP Code: 55 Event-Timestamp -->
		<AVP code="55" value="May 18, 2014 01:37:33.000000000" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="CAPv2_V.1.0@ericsson.com" vendor-id="193" />
	<!-- AVP Code: 1074 Subscription-Id-Location -->
	<AVP code="1074" value="353857000160" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 23 3GPP-MS-TimeZone -->
	<AVP code="23" value="0x40:00" vendor-id="10415" />
	<!-- AVP Code: 55 Event-Timestamp -->
	<AVP code="55" value="May 18, 2014 01:37:33.000000000" vendor-id="0" />
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/dcc/dcc_start.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- Session-Id -->
	<AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" />
	<!-- Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" />
   	<!-- Accounting-Record-Type -->
	<AVP code="480" value="2" />
	<!-- Acct-Interim-Interval -->
	<AVP code="85" value="10" />
	<!-- Destination-Host -->
	<AVP code="293" value="${Global.destIP}" />
	<!-- Vendor-Specific-Application-Id -->
	<AVP code="260" value="">
		<!-- Acct-Application-Id -->
		<AVP code="259" value="${Global.AcctAppID}" />
		<!-- Auth-Application-Id -->
		<AVP code="258" value="${Global.AuthAppID}" />
		<!-- Vendor-Id -->
		<AVP code="266" value="${Global.destVendorID}" />
	</AVP>	
	<!-- DCC Request CC number -->
	<AVP code="415" value="${Local.recordNumber}" />
	<!-- DCC Request CC type -->
	<AVP code="416" value="1" />
	<!-- Service-Context-Id -->
	<AVP code="461" value="${Global.serviceContextID}" />
	<!-- Auth-Application-Id -->
	<AVP code="258" value="${Global.AuthAppID}" />
</RequestData>

=== S-YOU/trace-samples/var_ffs/usecases_old/data/cipip_data_request_04.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<!--AVP code="263" value="c1-10-99-243-34-ggsn03.ericsson.se;1302790467;86" vendor-id="0" /-->
	<AVP code="263" value="${Global.sessionID}-${Global.nowunix}-${Global.randomSession}" vendor-id="0" />
	<!-- AVP Code: 30 Called-Station-Id -->
	<AVP code="30" value="67:79:74:73:70:36:30:30:36:2e:6b:61:2e:73:77:2e:65:72:69:63:73:73:6f:6e:2e:73:65" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<AVP code="415" value="3" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="2" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001234393437313132323435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="${Global.A-Number}" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc40000017323632343731313030303030303435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="262471100000045" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 456 Multiple-Services-Credit-Control -->
	<!-- Grouped data: 000001b04000000c00001900 -->
	<AVP code="456" value="" vendor-id="0">
		<!-- AVP Code: 432 Rating-Group -->
		<AVP code="432" value="6400" vendor-id="0" />
		<!-- AVP Code: 437 Requested-Service-Unit -->
		<AVP code="437" value="" vendor-id="0" />
		<!-- AVP Code: 446 Used-Service-Unit -->
		<!-- Grouped data: 0000019c4000001000000000000057f9 -->
		<AVP code="446" value="" vendor-id="0">
			<!-- AVP Code: 412 CC-Input-Octets -->
			<AVP code="412" value="22521" vendor-id="0" />
			<!-- AVP Code: 414 CC-Output-Octets -->
			<AVP code="414" value="339785" vendor-id="0" />
			<!-- AVP Code: 421 CC-Total-Octets -->
			<AVP code="421" value="362306" vendor-id="0" />
		</AVP>
		<!-- AVP Code: 1066 Charging-State-Information -->
		<AVP code="1066" value="01:01:81:02:81:03:01:02:01:03:00:04:01:ff:ff:82:13:01:00:00:00:00:ff:83:14:81:15:81:41:00:00:00:00:00:82:41:00:00:00:00:00:03:ff:ff:ff:ff:04:00:00:00:00:85:41:00:00:00:00:00:ff:02:01:03:01:04:00:ff:84:16:01:02:01:03:00:04:01:ff:85:18:01:00:00:00:00:82:19:81:1a:01:02:01:03:00:04:01:ff:82:1c:01:02:01:03:00:04:01:ff:83:1e:01:02:01:03:00:04:01:ff:84:20:01:02:01:03:00:04:01:ff:ff:ff:86:22:81:23:01:00:82:41:00:00:00:00:01:00:00:00:02:83:41:00:00:00:00:01:00:00:00:00:ff:02:01:03:01:04:00:ff:87:24:81:1d:01:00:00:02:f0:02:00:00:00:00:2a:08:7f:80:03:ff:ff:ff:fa:ff:02:01:03:01:04:00:ff:88:25:81:26:01:ff:ff:ff:ff:82:1d:01:00:00:02:f0:02:00:00:00:00:00:00:00:00:03:ff:ff:ff:fa:ff:03:00:00:00:00:00:00:00:00:ff:02:01:03:01:04:00:ff:89:27:81:34:00:00:00:00:00:02:01:03:01:04:00:ff:8a:28:81:29:81:35:00:00:00:00:11:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:82:2a:81:1b:01:00:00:00:00:00:00:00:00:ff:82:1d:01:ff:ff:ff:ff:02:00:00:00:00:00:00:00:00:03:00:00:00:00:ff:83:1f:01:00:00:00:00:00:00:00:00:02:00:00:00:00:00:00:00:00:03:00:00:00:00:00:00:00:00:ff:84:21:01:00:00:00:00:00:00:00:00:ff:ff:03:00:00:00:00:4d:ad:91:83:04:01:05:00:00:00:00:00:00:00:00:86:41:00:00:00:00:00:07:00:00:00:00:4d:ad:91:83:ff:02:01:03:01:04:00:ff:8b:2b:01:02:01:03:00:04:01:ff:8c:39:81:35:00:00:00:00:00:ff:8d:3a:01:02:01:03:00:04:01:ff:8e:3c:81:3d:01:00:01:02:00:00:03:00:00:01:2f:6e:00:67:b8:ff:02:01:03:01:04:00:ff:8f:3e:01:02:01:03:00:04:01:ff:90:43:81:44:00:45:00:00:00:00:02:ff:ff:ff:ff:ff:91:47:01:02:01:03:00:04:01:ff:ff" vendor-id="193" />
		<!-- AVP Code: 1068 Service-Session-Id -->
		<AVP code="1068" value="6400:-:2" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 461 Service-Context-Id -->
	<AVP code="461" value="6.32251@3gpp.org" vendor-id="0" />
	<!-- AVP Code: 1063 Access-Information -->
	<!-- Grouped data: 000000374000000cd1581012 -->
	<AVP code="1063" value="" vendor-id="193">
		<!-- AVP Code: 55 Event-Timestamp -->
		<AVP code="55" value="${Local.nowunix}" vendor-id="0" />
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="4" vendor-id="0" />
		<!-- AVP Code: 264 Origin-Host -->
		<AVP code="264" value="c1-10-99-243-34-ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 296 Origin-Realm -->
		<AVP code="296" value="ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 415 CC-Request-Number -->
		<AVP code="415" value="3" vendor-id="0" />
		<!-- AVP Code: 416 CC-Request-Type -->
		<AVP code="416" value="2" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="Ericsson_OCS_V1_0.0.0.7.32251@3gpp.org" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 1164 Ericsson-QoS-Profile -->
	<!-- Grouped data: 0000048dc0000010000000c100000003 -->
	<AVP code="1164" value="" vendor-id="193">
		<!-- AVP Code: 1165 Traffic-Class -->
		<AVP code="1165" value="00:00:00:03" vendor-id="193" />
		<!-- AVP Code: 1166 Guaranteed-Bit-Rate-For-Uplink -->
		<AVP code="1166" value="512000" vendor-id="193" />
		<!-- AVP Code: 1168 Guaranteed-Bit-Rate-For-Downlink -->
		<AVP code="1168" value="512000" vendor-id="193" />
	</AVP>
</RequestData>

=== S-YOU/trace-samples/var_ffs/usecases_old/data/cipip_data_request_05.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<!--AVP code="263" value="c1-10-99-243-34-ggsn03.ericsson.se;1302790467;86" vendor-id="0" /-->
	<AVP code="263" value="${Global.sessionID}" vendor-id="0" />
	<!-- AVP Code: 30 Called-Station-Id -->
	<AVP code="30" value="67:79:74:73:70:36:30:30:36:2e:6b:61:2e:73:77:2e:65:72:69:63:73:73:6f:6e:2e:73:65" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" vendor-id="0" />
	<!-- AVP Code: 295 Termination-Cause -->
	<AVP code="295" value="1" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<AVP code="415" value="4" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="3" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001234393437313132323435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="${Global.A-Number}" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc40000017323632343731313030303030303435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="262471100000045" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 456 Multiple-Services-Credit-Control -->
	<!-- Grouped data: 000001b04000000c000017d4 -->
	<AVP code="456" value="" vendor-id="0">
		<!-- AVP Code: 432 Rating-Group -->
		<AVP code="432" value="6100" vendor-id="0" />
		<!-- AVP Code: 446 Used-Service-Unit -->
		<!-- Grouped data: 0000019c400000100000000000000c26 -->
		<AVP code="446" value="" vendor-id="0">
			<!-- AVP Code: 412 CC-Input-Octets -->
			<AVP code="412" value="0" vendor-id="0" />
			<!-- AVP Code: 414 CC-Output-Octets -->
			<AVP code="414" value="0" vendor-id="0" />
			<!-- AVP Code: 421 CC-Total-Octets -->
			<AVP code="421" value="${Global.CC-Total-Octets}" vendor-id="0" />
		</AVP>
		<!-- AVP Code: 1066 Charging-State-Information -->
		<AVP code="1066" value="0x${Local.CDRData}" vendor-id="193" />
		<!-- AVP Code: 1068 Service-Session-Id -->
		<AVP code="1068" value="6100:-:1" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="Ericsson_OCS_V1_0.0.0.7.32251@3gpp.org" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 23 3GPP-MSTimeZone -->
	<AVP code="23" value="0x8001" vendor-id="10415" />
	<!-- AVP Code: 55 Event-Timestamp -->
	<AVP code="55" value="${Local.nowunix}" vendor-id="0" />
</RequestData>
