=== S-YOU/trace-samples/opt_ffs/schema/diameterRequest.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>
			Diameter definition schema.
		</xsd:documentation>
	</xsd:annotation>

	<!--ROOT element-->
	<xsd:element name="RequestData">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="AVP" type="AVP_Type" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!--Types-->
	<xsd:complexType name="AVP_Type">
		<xsd:sequence>
			<xsd:element name="AVP" type="AVP_Type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		
		<xsd:attribute name="code" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="optional"/>
		<xsd:attribute name="vendor-id" type="xsd:string" use="optional"/>
		<xsd:attribute name="mandatoryFlag" type="mandatoryFlag_type" use="optional"/>
		<xsd:attribute name="type" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:simpleType name="mandatoryFlag_type">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="true|false"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== S-YOU/trace-samples/opt_ffs/config/diameter/cir/cir_start.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- Session-Id -->
	<AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" />
	<!-- Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" />

	<!-- CC Request Type -->
	<AVP code="416" value="1" />

	<!-- CC Request Number -->
	<AVP code="415" value="${Local.recordNumber}" />

	<!-- Vendor-Specific-Application-Id -->
	<AVP code="260" value="">
		<!-- Acct-Application-Id -->
		<AVP code="259" value="${Global.AcctAppID}" />
		<!-- Auth-Application-Id -->
		<AVP code="258" value="${Global.AuthAppID}" />
		<!-- Vendor-Id -->
		<AVP code="266" value="${Global.destVendorID}" />
	</AVP>
	
	<!-- Service Context Id ****** Optional ****** -->
	<AVP code="461" value="abcdsci" />
	
	<!-- Charging Context Id -->
	<AVP code="1065" value="abcd" />
	
	<!-- Subscription Id -->
	<AVP code="443" value="">	
		<!-- Subscription Id Type -->
		<AVP code="450" value="0" />
		
		<!-- Subscription Id data -->
		<AVP code="444" value="xyz" />
	</AVP>
	
	<!-- Multiple Services Credit Control -->
	<AVP code="456" value="">
		<AVP code="1068" value="ssid"/>
	</AVP>
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/scap/scap_start.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- Session-Id -->
	<AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})"/>
	
	<!-- Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}"/>
	<!-- Accounting-Record-Type -->
	<AVP code="480" value="2"/>
	<!-- Accounting-Record-Number -->
	<AVP code="485" value="${Local.recordNumber}.set(0)"/>
	
	<!-- Subscription -Id -->
	<AVP code="553" value="">
		<AVP code="554" value="${Global.Subscription-Id-Data}"/>
		<!-- Auth-Application-Id -->
		<AVP code="555" value="${Global.Subscription-Id-Type}"/>
	</AVP>
	
	<!-- Requested Unit-->
	<AVP code="606" value="">
		<!-- Unit Type -->
		<AVP code="611" value="${Global.Unit-Type}"/>
		<!-- Unit-Value -->
		<AVP code="612" value="">
			<!-- Value Digits -->
			<AVP code="617" value="${Global.Requested-Unit-Digits}"/>
			<!-- Exponent -->
			<AVP code="616" value="${Global.Requested-Unit-Exponent}"/>
		</AVP>
		<!-- Currency-Code-->
		<AVP code="544" value="${Global.Currency-Code}"/>
	</AVP>
	
	<!-- Service Parameter Info -->
	<AVP code="607" value="">
		<!-- Time Zone -->
		<AVP code="13" value="${Global.TimeZone}"/>
	</AVP>
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/nasreq/nasreq_aar.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- Session-Id -->
	<!-- An AAR is an event type request with an exception that it can initiate a sesion -->
	<!-- To initiate a session through AAR, uncomment the line below and comment the line following it-->
	<!-- <AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" /> -->
	<AVP code="263" value="${Local.sessionID}"/>
	
	<!-- Auth-Application-Id -->
	<AVP code="258" value="${Global.AuthAppID}" />
	
	<!-- Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" />
	
	<!-- Auth-Request-Type -->
	<AVP code="274" value="1" />
	
	<!-- NAS-Identifier -->
	<AVP code="32" value="abc" />
	
	<!-- NAS-IP-Address -->
	<AVP code="4" value="067" />
	
	<!-- NAS-IPv6-Address -->
	<AVP code="95" value="067" />
	
	<!-- NAS-Port -->
	<AVP code="5" value="3872" />
	
	<!-- NAS-Port-Id -->
	<AVP code="87" value="portNAS" />
	
	<!-- Following values are supported for NAS-Port-Type -->
	<!-- 0   Async  -->
	<!-- 1   Sync -->
	<!-- 2   ISDN Sync -->
	<!-- 3   ISDN Async V.120 -->
	<!-- 4   ISDN Async V.110 -->
	<!-- 5   Virtual -->
	<!-- 6   PIAFS -->
	<!-- 7   HDLC Clear Channel -->
	<!-- 8   X.25 -->
	<!-- 9   X.75 -->
	<!-- 10   G.3 Fax -->
	<!-- 11   SDSL - Symmetric DSL -->
	<!-- 12   ADSL-CAP - Asymmetric DSL, Carrierless Amplitude Phase Modulation -->
	<!-- 13   ADSL-DMT - Asymmetric DSL, Discrete Multi-Tone -->
	<!-- 14   IDSL - ISDN Digital Subscriber Line -->
	<!-- 15   Ethernet -->
	<!-- 16   xDSL - Digital Subscriber Line of unknown type -->
	<!-- 17   Cable -->
	<!-- 18   Wireless - Other -->
	<!-- 19   Wireless - IEEE 802.11 -->
	<!-- 20   Token-Ring   [RAD802.1X] -->
	<!-- 21   FDDI         [RAD802.1X] -->
	<!-- 22   Wireless - CDMA2000 -->
	<!-- 23   Wireless - UMTS -->
	<!-- 24   Wireless - 1X-EV -->
	<!-- 25   IAPP    [IEEE 802.11f] -->

	<!-- NAS-Port-Type -->
	<AVP code="61" value="0" />
	
	<!-- Origin-AAA-Protocol -->
	<AVP code="408" value="1" />
	
	<!-- Origin-State-Id -->
	<AVP code="278" value="2" />
		
	<!-- Port-Limit -->
	<AVP code="62" value="10" />
	
	<!-- User-Name -->
	<AVP code="1" value="abc" />
	
	<!-- User-Password -->
	<AVP code="2" value="abc" />
	
	<!-- Following values are supported for Service-Type -->
       <!-- 1  Login -->
       <!-- 2  Framed -->
       <!-- 3  Callback Login -->
       <!-- 4  Callback Framed -->
       <!-- 5  Outbound -->
       <!-- 6  Administrative -->
       <!-- 7  NAS Prompt -->
       <!-- 8  Authenticate Only -->
       <!-- 9  Callback NAS Prompt -->
       <!-- 10  Call Check -->
       <!-- 11  Callback Administrative -->
       <!-- 12  Voice -->
       <!-- 13  Fax -->
       <!-- 14  Modem Relay -->
       <!-- 15  IAPP-Register   [IEEE 802.11f] -->
       <!-- 16  IAPP-AP-Check   [IEEE 802.11f] -->
       <!-- 17  Authorize Only  [RADDynAuth] -->	
	<!-- Service-Type -->
	<AVP code="6" value="1" />
	
	<!-- State -->
	<AVP code="24" value="xyz" />
	
	<!-- Authorization-Lifetime -->
	<AVP code="291" value="0" />
	
	<!-- Auth-Grace-Period -->
	<AVP code="276" value="100" />
	
	<!-- Auth-Session-State -->
	<AVP code="277" value="0" />
	
	<!-- Callback-Number -->
	<AVP code="19" value="221133" />
	
	<!--  Called-Station-Id -->
	<AVP code="30" value="221133" />
	
	<!--  Calling-Station-Id -->
	<AVP code="31" value="112244" />
	
		<!-- Supported values for Originating Line Info -->
		<!--  Value   Description -->

		<!--   00    Plain Old Telephone Service (POTS) -->
		<!--   01    Multiparty Line (more than 2) -->
      	<!--   02    ANI Failure -->
      	<!--   03    ANI Observed -->
      	<!--   04    ONI Observed -->
      	<!--   05    ANI Failure Observed -->
      	<!--   06    Station Level Rating -->
      	<!--   07    Special Operator Handling Required -->
      	<!--   08    InterLATA Restricted -->
      	<!--   10    Test Call -->
      	<!--   20    Automatic Identified Outward Dialing (AIOD) -->
      	<!--   23    Coin or Non-Coin -->
      	<!--   24    Toll Free Service (Non-Pay Origination) -->
      	<!--   25    Toll Free Service (Pay Origination) -->
      	<!--   27    Toll Free Service (Coin Control Origination) -->
      	<!--   29    Prison/Inmate Service -->
      	<!--   30-32 Intercept -->
      	<!--   30    Intercept (Blank) -->
      	<!--   31    Intercept (Trouble) -->
      	<!--   32    Intercept (Regular) -->
      	<!--   34    Telco Operator Handled Call -->
      	<!--   40-49 Unrestricted Use -->
      	<!--   52    Outward Wide Area Telecommunications Service (OUTWATS) -->
      	<!--   60    Telecommunications Relay Service (TRS)(Unrestricted) -->
      	<!--   61    Cellular/Wireless PCS (Type 1) -->
      	<!--   62    Cellular/Wireless PCS (Type 2) -->
      	<!--   63    Cellular/Wireless PCS (Roaming) -->
      	<!--   66    TRS (Hotel) -->
      	<!--   67    TRS (Restricted) -->
      	<!--   70    Pay Station, No Coin Control -->
      	<!--   93    Access for Private Virtual Network Service -->
	
	<!--  Originating-Line-Info -->
	<AVP code="94" value="00" />
	
	
	
	<!--  Connect-Info -->
	<AVP code="77" value="28800 V42BIS/LAPM" />
	
	<!--  CHAP-Auth -->
	<AVP code="402" value="">	
		<!-- Chap Algorithm -->
		<AVP code="403" value="5" />
		
		<!-- CHAP-Ident -->
		<AVP code="404" value="0" />
		
		<!-- Chap response -->
		<AVP code="405" value="01234" />
	</AVP>		
	
	<!--  CHAP-Challenge -->
	<AVP code="60" value="0101" />
	
	<!-- Supported values for Framed-Compression -->
	<!-- 0  None -->
	<!-- 1  VJ TCP/IP header compression -->
	<!-- 2  IPX header compression -->
    <!-- 3  Stac-LZS compression -->
        
	<!--  Framed-Compression -->
	<AVP code="13" value="0" />
	
	<!--  Framed-Interface-Id -->
	<AVP code="96" value="1121" />
	
	<!--  Framed-IP-Address -->
	<AVP code="8" value="0xFFFFFFFF" />
	
	<!--  Framed-IPv6-Prefix -->
	<AVP code="97" value="001" />
	
	<!--  Framed-IP-Netmask -->
	<AVP code="9" value="0xFFFFFFFF" />
	
	<!--  Framed-MTU -->
	<AVP code="12" value="64" />
	
	<!-- Supported values for Framed Protocol -->
	<!-- 1  PPP -->
	<!-- 2  SLIP -->
	<!-- 3  AppleTalk Remote Access Protocol (ARAP) -->
	<!-- 4  Gandalf proprietary SingleLink/MultiLink protocol -->
	<!-- 5  Xylogics proprietary IPX/SLIP -->
	<!-- 6  X.75 Synchronous -->

	<!-- Framed-Protocol -->
	<AVP code="7" value="1" />
	
	<!-- This AVP MUST NOT be present if either the User-Password or the CHAP-Auth AVP is present -->
	<!--  ARAP-Password -->
	<!-- <AVP code="70" value="" /> -->
	
	<!--  ARAP-Security -->
	<AVP code="73" value="111" />

	<!-- Actually for running either Authentciation _id should be non zero 
	or Accounting and application-Id both need to be defined otherwise the stack will give a no route defined mmessage 
	-->
	<AVP code="260" value="">
		<!-- Acct-Application-Id -->
		<AVP code="259" value="${Global.AcctAppID}" />
		<!-- Auth-Application-Id -->
		<AVP code="258" value="${Global.AuthAppID}" />
		<!-- Vendor-Id -->
		<AVP code="266" value="${Global.destVendorID}" />
	</AVP>
	
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/remoteChargingData/create_event_cache.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">

    <!-- Origin-Host -->
    <AVP code="264" value="${Global.ownIP}" />
    
    <!-- Destination-Realm -->    
    <AVP code="283" value="${Global.destRealm}" />
    
    <!--  Origin Realm -->
    <AVP code="296" value="${Global.ownRealm}" />

    <!--  Session Id -->
    <AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" />
    
    <!-- Vendor-Specific-Application-Id -->
    <AVP code="260" value="">
        <!-- Auth-Application-Id -->
        <AVP code="258" value="${Global.AuthAppID}" />
        <!-- Vendor-Id -->
        <AVP code="266" value="${Global.destVendorID}" />
    </AVP>

    <!-- CC Request Number -->
    <AVP code="415" value="${Local.recordNumber}" />

	<!-- CC Request Type -->
	<AVP code="416" value="4" />

    <!--  Requested Action -->
    <AVP code="436" value="2" />
    
    <!-- Subscription Id -->
    <AVP code="443" value="">
        <!-- Subscription Id data -->
        <AVP code="444" value="1555666490002" />
        <!-- Subscription Id Type -->
        <AVP code="450" value="0" />
    </AVP>

    <!-- Charging Context Id -->
    <AVP code="1065" vendor-id="193" value="InternalRequest"/>

    <!-- Remote-Charging-Data -->
    <AVP code="1345" vendor-id="193" value="ServiceProviderId=ReratingService;
                                            SegmentId=cha1;
                                            TransactionId=TransactionId;                                                
                                            PayloadTransactionId=TransactionId;
                                            CommunicationId=1;
                                            CustomerId=11111;
                                            ContractId=111110;    

                                            Rerating.Operation=CREATE_EVENT_CACHE;
                                            Rerating.TransactionId=TransactionId;
                                            Rerating.CommunicationId=1;
                                            Rerating.CustomerId=11111;
                                            Rerating.ContractId=111110;
                                            Rerating.OrderId=3a;                       
                                           " />
            
    <!-- Remote-Charging-Data-Version -->
        <AVP code="1346" vendor-id="193" value="0_1_0" />

</RequestData>

=== S-YOU/trace-samples/var_ffs/usecases/data/cipip_data_request_03.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">
	<!-- AVP Code: 263 Session-Id -->
	<!--AVP code="263" value="c1-10-99-243-34-ggsn03.ericsson.se;1302790467;86" vendor-id="0" /-->
	<AVP code="263" value="${Global.sessionID}" vendor-id="0" />
	<!-- AVP Code: 30 Called-Station-Id -->
	<AVP code="30" value="indosat.gprs" vendor-id="0" />
	<!-- AVP Code: 260 Vendor-Specific-Application-Id -->
	<!-- Grouped data: 000001024000000c01000010 -->
	<AVP code="260" value="" vendor-id="0">
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="16777232" vendor-id="0" />
		<!-- AVP Code: 266 Vendor-Id -->
		<AVP code="266" value="193" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 283 Destination-Realm -->
	<AVP code="283" value="${Global.destRealm}" vendor-id="0" />
	<!-- AVP Code: 415 CC-Request-Number -->
	<AVP code="415" value="2" vendor-id="0" />
	<!-- AVP Code: 416 CC-Request-Type -->
	<AVP code="416" value="2" vendor-id="0" />
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc4000001234393437313132323435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="${Global.A-Number}" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="0" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 443 Subscription-Id -->
	<!-- Grouped data: 000001bc40000017323632343731313030303030303435 -->
	<AVP code="443" value="" vendor-id="0">
		<!-- AVP Code: 444 Subscription-Id-Data -->
		<AVP code="444" value="51010100023400" vendor-id="0" />
		<!-- AVP Code: 450 Subscription-Id-Type -->
		<AVP code="450" value="1" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 456 Multiple-Services-Credit-Control -->
	<!-- Grouped data: 000001b04000000c000017d4 -->
	<AVP code="456" value="" vendor-id="0">
		<!-- AVP Code: 432 Rating-Group -->
		<AVP code="432" value="22152" vendor-id="0" />
		<!-- AVP Code: 437 Requested-Service-Unit -->
		<AVP code="437" value="" vendor-id="0" />
		<!-- AVP Code: 1068 Service-Session-Id -->
		<AVP code="1068" value="23110:-:1" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 461 Service-Context-Id -->
	<AVP code="461" value="Ericsson_OCS_V1_0.0.0.7.32251@3gpp.org" vendor-id="0" />
	<!-- AVP Code: 1063 Access-Information -->
	<!-- Grouped data: 000000374000000cd1581003 -->
	<AVP code="1063" value="" vendor-id="193">
		<!-- AVP Code: 55 Event-Timestamp -->
		<AVP code="55" value="${Global.startOfCall}" vendor-id="0" />
		<!-- AVP Code: 258 Auth-Application-Id -->
		<AVP code="258" value="4" vendor-id="0" />
		<!-- AVP Code: 264 Origin-Host -->
		<AVP code="264" value="c1-10-99-243-34-ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 296 Origin-Realm -->
		<AVP code="296" value="ggsn03.ericsson.se" vendor-id="0" />
		<!-- AVP Code: 415 CC-Request-Number -->
		<AVP code="415" value="1" vendor-id="0" />
		<!-- AVP Code: 416 CC-Request-Type -->
		<AVP code="416" value="2" vendor-id="0" />
	</AVP>
	<!-- AVP Code: 1065 Charging-Context-Id -->
	<AVP code="1065" value="Ericsson_OCS_V1_0.0.0.7.32251@3gpp.org" vendor-id="193" />
	<!-- AVP Code: 1083 CIP-IP-Version -->
	<AVP code="1083" value="R1A" vendor-id="193" />
	<!-- AVP Code: 1164 Ericsson-QoS-Profile -->
	<!-- Grouped data: 0000048dc0000010000000c100000003 -->
	<AVP code="1164" value="" vendor-id="193">
		<!-- AVP Code: 1165 Traffic-Class -->
		<AVP code="1165" value="00000003" vendor-id="193" />
		<!-- AVP Code: 1166 Guaranteed-Bit-Rate-For-Uplink -->
		<AVP code="1166" value="512000" vendor-id="193" />
		<!-- AVP Code: 1168 Guaranteed-Bit-Rate-For-Downlink -->
		<AVP code="1168" value="512000" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 1170 Ericsson-Geographical-Location -->
	<!-- Grouped data: 00000493c0000011000000c13234303939 -->
	<AVP code="1170" value="" vendor-id="193">
		<!-- AVP Code: 1171 Ericsson-Location-MCC-MNC -->
		<AVP code="1171" value="51001" vendor-id="193" />
		<!-- AVP Code: 1172 Ericsson-Location-Area-Code -->
		<AVP code="1172" value="01:d8" vendor-id="193" />
		<!-- AVP Code: 1174 Ericsson-Geo-Location-Cell-Identity -->
		<AVP code="1174" value="00:03" vendor-id="193" />
	</AVP>
	<!-- AVP Code: 2 3GPP-Charging-Id -->
	<AVP code="2" value="18400345" vendor-id="10415" />
	<!-- AVP Code: 3 3GPP-PDP type -->
	<AVP code="3" value="0" vendor-id="10415" />
	<!-- AVP Code: 8 3GPP-IMSI MCC-MNC -->
	<AVP code="8" value="51001" vendor-id="10415" />
	<!-- AVP Code: 10 3GPP-NSAPI -->
	<AVP code="10" value="5" vendor-id="10415" />
	<!-- AVP Code: 12 3GPP-Selection-Mode -->
	<AVP code="12" value="1" vendor-id="10415" />
	<!-- AVP Code: 13 3GPP-Charging-Characteristics -->
	<AVP code="13" value="0000" vendor-id="10415" />
	<!-- AVP Code: 18 3GPP-SGSN MCC-MNC -->
	<AVP code="18" value="51001" vendor-id="10415" />
	<!-- AVP Code: 21 3GPP-RAT-Type -->
	<AVP code="21" value="0x01" vendor-id="10415" />
	<!-- AVP Code: 23 3GPP-MSTimeZone -->
	<AVP code="23" value="0x2300" vendor-id="10415" />
	<!-- AVP Code: 847 GGSN-Address -->
	<AVP code="847" value="1.1.1.1" vendor-id="10415" />
	<!-- AVP Code: 1227 PDP-Address -->
	<AVP code="1227" value="53.18.0.2" vendor-id="10415" />
	<!-- AVP Code: 1228 SGSN-Address -->
	<AVP code="1228" value="10.99.1.129" vendor-id="10415" />
	<!-- AVP Code: 55 Event-Timestamp -->
	<AVP code="55" value="${Local.nowunix}" vendor-id="0" />
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/remoteChargingData/cdr_processing.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">

    <!-- Origin-Host -->
    <AVP code="264" value="${Global.ownIP}" />
    
    <!-- Destination-Realm -->    
    <AVP code="283" value="${Global.destRealm}" />
    
    <!--  Origin Realm -->
    <AVP code="296" value="${Global.ownRealm}" />

    <!--  Session Id -->
    <AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" />
    
    <!-- Vendor-Specific-Application-Id -->
    <AVP code="260" value="">
        <!-- Auth-Application-Id -->
        <AVP code="258" value="${Global.AuthAppID}" />
        <!-- Vendor-Id -->
        <AVP code="266" value="${Global.destVendorID}" />
    </AVP>

    <!-- CC Request Number -->
    <AVP code="415" value="${Local.recordNumber}" />

    <!-- CC Request Type -->
    <AVP code="416" value="4" />

    <!--  Requested Action -->
    <AVP code="436" value="2" />
    
    <!-- Subscription Id -->
    <AVP code="443" value="">
        <!-- Subscription Id data -->
        <AVP code="444" value="1555666490002" />
        <!-- Subscription Id Type -->
        <AVP code="450" value="0" />
    </AVP>

    <!-- Charging Context Id -->
    <AVP code="1065" vendor-id="193" value="InternalRequest"/>

    <AVP code="1345" vendor-id="193"
                value="ServiceProviderId=CdrProcessingService;
                       SegmentId=cha1;          
                       TransactionId=TransactionId;                                                                       
                       CommunicationId=aCommunicationId;
                       CustomerId=11111;
                       ContractId=111110;
                       
                       TriggerTime=2014-05-13T09:12:16+02:00;                                                                                               
                       UnitType=Time;
                       UnitValue=100;
                       ChargingContextId=CdrProcessing;
                       PayloadDuplicateDetectionId=PayloadDuplicateDetectionId;
                       CdrInformation.FileName=BxRecord1234.cdr;
                       CdrInformation.RecordType=0;
                       CdrInformation.OriginatingNode=CdrGenerator5;           
                       CdrInformation.SequenceNumber=21;
                       CdrInformation.TimeStamp=20140203T091400000+0100;     
                       DynamicData.RecordType=DYNAMIC_INTEGER:0;
                       DynamicData.ServedMSISDN=DYNAMIC_ADDRESS_STRING:{MSISDN_INTERNATIONAL,4644123456};
     "/>
                                            
    <!-- Remote-Charging-Data-Version -->
        <AVP code="1346" vendor-id="193" value="0_1_0" />

</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/diameter/remoteChargingData/account_adjustment.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/diameterRequest.xsd">

    <!-- Origin-Host -->
    <AVP code="264" value="${Global.ownIP}" />
    
    <!-- Destination-Realm -->    
    <AVP code="283" value="${Global.destRealm}" />
    
    <!--  Origin Realm -->
    <AVP code="296" value="${Global.ownRealm}" />

    <!--  Session Id -->
    <AVP code="263" value="${Local.sessionID}.set(${Global.aIncreasingValue})" />
    
    <!-- Vendor-Specific-Application-Id -->
    <AVP code="260" value="">
        <!-- Auth-Application-Id -->
        <AVP code="258" value="${Global.AuthAppID}" />
        <!-- Vendor-Id -->
        <AVP code="266" value="${Global.destVendorID}" />
    </AVP>

    <!-- CC Request Number -->
    <AVP code="415" value="${Local.recordNumber}" />

	<!-- CC Request Type -->
	<AVP code="416" value="4" />

    <!--  Requested Action -->
    <AVP code="436" value="2" />
    
    <!-- Subscription Id -->
    <AVP code="443" value="">
        <!-- Subscription Id data -->
        <AVP code="444" value="1555666490002" />
        <!-- Subscription Id Type -->
        <AVP code="450" value="0" />
    </AVP>

    <!-- Charging Context Id -->
    <AVP code="1065" vendor-id="193" value="InternalRequest"/>

    <!-- Remote-Charging-Data -->    
    <!--      {0AccountAdjustmentService  cha1(PayloadTransactionIdd TransactionId  CommunicationId 11111    11ï¿½ï¿½ï¿½     0_1_0} -->    
    <!--     Request with both product and billing account is not allowed -->
    


<!-- BillingAccountUpdate Example: -->
<!--                 BillingAccountUpdate.BillingAccountId=11; -->
<!--                 BillingAccountUpdate.Operation=1; -->
<!--                 BillingAccountUpdate.DeltaValue=10000; -->
<!--                 BillingAccountUpdate.Decimals=2; -->

<!-- ProductAccountUpdate Example: -->
<!--                 ProductAccountUpdates.ContractId=11111; -->
<!--                 ProductAccountUpdates.ProductId=Voice; -->
<!--                 ProductAccountUpdates.ProductAccountId=11; -->
<!--                 ProductAccountUpdates.DeltaValue=10000; -->
<!--                 ProductAccountUpdates.Decimals=2; -->
<!--                 ProductAccountUpdates.Operation=1; -->
                                            
    <AVP code="1345" vendor-id="193" value="ServiceProviderId=AccountAdjustmentService;
                                            SegmentId=cha1;
                                            TransactionId=TransactionId;                                                
                                            PayloadTransactionId=TransactionId;
                                            CommunicationId=1;
                                            CustomerId=11111;
                                            ContractId=111110;
                                            
                                            BillingAccountUpdate.BillingAccountId=11;
                                            BillingAccountUpdate.Operation=1;
                                            BillingAccountUpdate.DeltaValue=10000;
                                            BillingAccountUpdate.Decimals=2;
                                            " />
            
    <!-- Remote-Charging-Data-Version -->
        <AVP code="1346" vendor-id="193" value="0_1_0" />

</RequestData>
