=== S-YOU/trace-samples/opt_ffs/schema/dictionaryOnline.xsd
<!--
XML Schema for Diameter base protocol addon.
The following schema validates the XML syntax that defines the Diameter AVP's.

Author: Henrik Pettersson <henrik.a.pettersson@ericsson.com>
Updated: Anders Olander <anders.olander@ericsson.com>
Copyright Ericsson AB, Sweden 2005
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- Top Tag -->
	<xs:element name="Protocol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SupportedVendorId" type="Svi_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
				<xs:element name="AVP_Def" type="AVP_Def_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
				
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Request" type="Message_Type">
						<xs:unique name="Request_Avp_Uniquename">
							<xs:selector xpath="AVP"></xs:selector>
							<!-- <xs:field xpath="@name"/> -->
							<xs:field xpath="@alias"></xs:field>
						</xs:unique>
					</xs:element>
				</xs:choice>
				
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Response" type="Message_Type">
						<xs:unique name="Response_Avp_Uniquename">
							<xs:selector xpath="AVP"></xs:selector>
							<!-- <xs:field xpath="@name"/> -->
							<xs:field xpath="@alias"></xs:field>
						</xs:unique>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			
			<xs:attribute name="id" type="id_type" use="optional"></xs:attribute>
			<xs:attribute name="version" type="xs:decimal" use="optional"></xs:attribute>
			<xs:attribute name="name" type="name_type" use="optional"></xs:attribute>
			<xs:attribute name="spec" type="xs:string" use="optional"></xs:attribute>
			<xs:attribute name="isHeaderInformationRequired" type="xs:boolean" use="optional" default="false"></xs:attribute>
			<xs:attribute name="comment" type="xs:string" use="optional"></xs:attribute>
		</xs:complexType>
		
		<xs:unique name="UniqueVendorId">
			<xs:selector xpath="SupportedVendorId"></xs:selector>
			<xs:field xpath="@vendorId"></xs:field>
		</xs:unique>
		
		<xs:unique name="AVP_DefUniqueCode">
			<xs:selector xpath="AVP_Def"></xs:selector>
			<xs:field xpath="@code"></xs:field>
			<xs:field xpath="@vendorId"></xs:field>
		</xs:unique>
		
		<!--
		<xs:keyref name="AVPMatchingAVP_Def" refer="AVP_defKey">
			<xs:selector xpath=".//AVP"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:keyref>
		
		<xs:key name="AVP_defKey">
			<xs:selector xpath="AVP_Def"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:key>
		-->
		
		<xs:unique name="Request_condition_unique">
			<xs:selector xpath="Request/Condition"></xs:selector>
			<xs:field xpath="@key"></xs:field>
			<xs:field xpath="@value"></xs:field>
		</xs:unique>
		
		<xs:unique name="Response_condition_unique">
			<xs:selector xpath="Response/Condition"></xs:selector>
			<xs:field xpath="@key"></xs:field>
			<xs:field xpath="@value"></xs:field>
		</xs:unique>
	</xs:element>
	
	<xs:complexType name="Svi_Type">
		<xs:attribute name="vendorId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Message_Type">
		<xs:sequence>
			<xs:element name="Condition" type="Condition_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element name="AVP" type="AVP_Type" minOccurs="1" maxOccurs="unbounded"></xs:element>
			<xs:element name="AVP_Any" type="AVP_Any_Type" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		
		<xs:attribute name="name" type="name_type" use="required"></xs:attribute>
		<xs:attribute name="ignoreMandatoryFlag" type="xs:boolean" use="optional" default="false"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Condition_Type">
		<xs:attribute name="key" type="key_type" use="required"></xs:attribute>
		<xs:attribute name="value" type="condition_value_type" use="required"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
	</xs:complexType>
	
	<!-- The AVP Tag Definition type. -->
	<xs:complexType name="AVP_Def_Type">
		<xs:sequence>
			<xs:element name="EnumValue" type="EnumValue_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		
		<xs:attribute name="name" type="name_type" use="required"></xs:attribute>
		<xs:attribute name="code" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="vendorId" type="VendorIdType" use="optional" default="0"></xs:attribute>
		<xs:attribute name="type" type="AVP_Datatype" use="required"></xs:attribute>
		<xs:attribute name="mandatoryFlag" type="AVP_Mandatoryflag_Datatype" use="optional"></xs:attribute>
		<xs:attribute name="format" type="format_type" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="AVP_Type">
		<xs:choice>
			<xs:element name="EnumValue" type="EnumValue_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:element name="Index" type="Index_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
			<xs:sequence>
				<xs:element name="AVP" type="AVP_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
				<xs:element name="AVP_Any" type="AVP_Any_Type" minOccurs="0" maxOccurs="1"></xs:element>
			</xs:sequence>
		</xs:choice>
		
		<xs:attribute name="name" type="name_type" use="required"></xs:attribute>
		<xs:attribute name="defaultValue" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="occurrence" type="AVP_Occurrence" use="optional"></xs:attribute>
		<xs:attribute name="avpSep" type="sepChar" use="optional" default="-"></xs:attribute>
		<xs:attribute name="code" type="xs:nonNegativeInteger" use="optional"></xs:attribute>
		<xs:attribute name="vendorId" type="xs:nonNegativeInteger" use="optional"></xs:attribute>
		<xs:attribute name="type" type="AVP_Datatype" use="optional"></xs:attribute>
		<xs:attribute name="mandatoryFlag" type="xs:boolean" use="optional"></xs:attribute>
		<xs:attribute name="alias" type="alias_type" use="optional"></xs:attribute>
		<xs:attribute name="mapping" type="Mappings" use="optional" default="normal"></xs:attribute>
		<xs:attribute name="listSep" type="sepChar" use="optional" default=";"></xs:attribute>
		<xs:attribute name="counter" type="counter_type" use="optional"></xs:attribute>
		<xs:attribute name="indexSep" type="sepChar" use="optional" default="-"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="AVP_Any_Type">
		<xs:attribute name="name" type="name_type" use="optional"></xs:attribute>
		<xs:attribute name="counter" type="counter_type" use="optional"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
		<xs:attribute name="defaultValue" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="occurrence" type="AVP_Occurrence" use="optional"></xs:attribute>
	</xs:complexType>
	
	<!-- The possible AVP datatypes values. -->
	<xs:simpleType name="AVP_Datatype">
		<xs:restriction base="xs:NMTOKEN">
			<!-- Base types -->
			<xs:enumeration value="OctetString"></xs:enumeration>
			<xs:enumeration value="Integer32"></xs:enumeration>
			<xs:enumeration value="Integer64"></xs:enumeration>
			<xs:enumeration value="Float32"></xs:enumeration>
			<xs:enumeration value="Float64"></xs:enumeration>
			<xs:enumeration value="Unsigned32"></xs:enumeration>
			<xs:enumeration value="Unsigned64"></xs:enumeration>
			<xs:enumeration value="Grouped"></xs:enumeration>
			<!-- Derived types -->
			<xs:enumeration value="Address"></xs:enumeration>
			<xs:enumeration value="Enumerated"></xs:enumeration>
			<xs:enumeration value="Time"></xs:enumeration>
			<xs:enumeration value="UTF8String"></xs:enumeration>
			<xs:enumeration value="IPFilterRule"></xs:enumeration>
			<xs:enumeration value="DiameterIdentity"></xs:enumeration>
			<xs:enumeration value="DiameterURI"></xs:enumeration>
			<xs:enumeration value="IPFilterRule"></xs:enumeration>
			<xs:enumeration value="QoSFilterRule"></xs:enumeration>
			<!-- Special Types -->
			<xs:enumeration value="OctetString:str"></xs:enumeration>
			<xs:enumeration value="Opaque"></xs:enumeration>
			<xs:enumeration value="Address32"></xs:enumeration>
			<xs:enumeration value="Date"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- The possible AVP madatory flag values. -->
	<xs:simpleType name="AVP_Mandatoryflag_Datatype">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="yes"></xs:enumeration>
			<xs:enumeration value="no"></xs:enumeration>
			<xs:enumeration value="true"></xs:enumeration>
			<xs:enumeration value="false"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- The possible AVP occurrence flag values . -->
	<xs:simpleType name="AVP_Occurrence">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"></xs:enumeration>
			<xs:enumeration value="0+"></xs:enumeration>
			<xs:enumeration value="0-1"></xs:enumeration>
			<xs:enumeration value="1"></xs:enumeration>
			<xs:enumeration value="1+"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="EnumValue_Type">
		<xs:attribute name="value" type="xs:integer" use="optional"></xs:attribute>
		<xs:attribute name="alias" type="alias_type" use="optional"></xs:attribute>
		<xs:attribute name="comment" type="comment_type" use="optional"></xs:attribute>
		<xs:attribute name="min" type="xs:nonNegativeInteger" use="optional"></xs:attribute>
		<xs:attribute name="max" type="xs:nonNegativeInteger" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Index_Type">
		<xs:attribute name="value" type="value_type" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="Mappings">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="normal"></xs:enumeration>
			<xs:enumeration value="none"></xs:enumeration>
			<xs:enumeration value="array"></xs:enumeration>
			<xs:enumeration value="index"></xs:enumeration>
			<xs:enumeration value="list"></xs:enumeration>
			<xs:enumeration value="group"></xs:enumeration>
			<xs:enumeration value="sum"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="sepChar">
		<xs:restriction base="xs:string">
			<xs:length value="1" fixed="true"></xs:length>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- VendorId boundries -->
	<xs:simpleType name="VendorIdType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"></xs:minInclusive>
			<xs:maxInclusive value="2147483647"></xs:maxInclusive>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="value_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]|[A-Z]|[0-9]|-|_)+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="key_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]|[A-Z]|[0-9]|-|_)+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="name_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="( )*([a-z]|[A-Z]|[0-9]|-|_|:)+([a-z]|[A-Z]|[0-9]|-|_|:| )*"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="counter_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]|[A-Z]|[0-9]|-|_)+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- HI62242: Removed restriction from format type to include special symbols in date text -->
	<xs:simpleType name="format_type">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="condition_value_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]|[A-Z]|[0-9]|-|_|.)+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="alias_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-z]|[A-Z]|[0-9]|-|_|.)+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="id_type">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="comment_type">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"></xs:minLength>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== S-YOU/trace-samples/opt_ffs/config/diameter/dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocol version="1.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="schema/dictionaryOnline.xsd">
	
<!-- Diameter Base Protocol RFC3588 -->
	<AVP_Def name="Accounting-Record-Number" code="485" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Accounting-Record-Type" code="480" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="1" comment="EVENT_RECORD" />
		<EnumValue value="2" comment="START_RECORD" />
		<EnumValue value="3" comment="INTERIM_RECORD" />
		<EnumValue value="4" comment="STOP_RECORD" />
	</AVP_Def>
	<AVP_Def name="Accounting-Realtime-Required" code="483" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="1" comment="DELIVER_AND_GRANT" />
		<EnumValue value="2" comment="GRANT_AND_STORE" />
		<EnumValue value="3" comment="GRANT_AND_LOSE" />
	</AVP_Def>
	<AVP_Def name="Accounting-Session-Id" code="44" type="OctetString" mandatoryFlag="true" />
	<AVP_Def name="Accounting-Sub-Session-Id" code="287" type="Unsigned64" mandatoryFlag="true" />
	<AVP_Def name="Acct-Application-Id" code="259" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="Diameter Common Messages" />
		<EnumValue value="1" comment="Diameter NASREQ Application" />
		<EnumValue value="2" comment="Diameter Mobile IPv4 Application" />
		<EnumValue value="3" comment="Diameter Base Accounting" />
		<EnumValue value="16777216" comment="3GPP CX/DX" />
		<EnumValue value="16777217" comment="3GPP Sh" />
		<EnumValue value="16777218" comment="3GPP Re/Rf" />
		<EnumValue value="16777219" comment="3GPP Wx" />
		<EnumValue value="16777220" comment="3GPP Zn" />
		<EnumValue value="16777221" comment="3GPP Zh" />
		<EnumValue value="16777222" comment="3GPP Gq" />
		<EnumValue value="16777223" comment="3GPP Gmb" />
		<EnumValue value="16777302" comment="3GPP Sy" />
		<EnumValue value="16777303" comment="3GPP Sd" />
		<EnumValue value="16777304" comment="Ericsson Sy"/>
	</AVP_Def>
	<AVP_Def name="Acct-Interim-Interval" code="85" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Acct-Multi-Session-Id" code="50" type="UTF8String" mandatoryFlag="true" />
	<AVP_Def name="Authorization-Lifetime" code="291" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Auth-Application-Id" code="258" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Auth-Grace-Period" code="276" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Auth-Request-Type" code="274" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="1" comment="AUTHENTICATE_ONLY" />
		<EnumValue value="2" comment="AUTHORIZE_ONLY" />
		<EnumValue value="3" comment="AUTHORIZE_AUTHENTICATE" />
	</AVP_Def>
	<AVP_Def name="Auth-Session-State" code="277" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="STATE_MAINTAINED" />
		<EnumValue value="1" comment="NO_STATE_MAINTAINED" />
	</AVP_Def>
	<AVP_Def name="Class" code="25" type="OctetString" mandatoryFlag="true" />
	<AVP_Def name="Destination-Host" code="293" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Destination-Realm" code="283" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Disconnect-Cause" code="273" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="REBOOTING" />
		<EnumValue value="1" comment="BUSY" />
		<EnumValue value="2" comment="DO_NOT_WANT_TO_TALK_TO_YOU" />
	</AVP_Def>
	<AVP_Def name="E2E-Sequence" code="300" type="Grouped" mandatoryFlag="true" />
	<AVP_Def name="Error-Message" code="281" type="UTF8String" mandatoryFlag="false" />
	<AVP_Def name="Error-Reporting-Host" code="294" type="DiameterIdentity" mandatoryFlag="false" />
	<AVP_Def name="Event-Timestamp" code="55" type="Time" mandatoryFlag="true" />
	<AVP_Def name="Experimental-Result" code="297" type="Grouped" mandatoryFlag="true" />
	<AVP_Def name="Experimental-Result-Code" code="298" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Failed-AVP" code="279" type="Grouped" mandatoryFlag="true" />
	<AVP_Def name="Firmware-Revision" code="267" type="Unsigned32" mandatoryFlag="false" />
	<AVP_Def name="Host-IP-Address" code="257" type="Address" mandatoryFlag="true" />
	<AVP_Def name="Inband-Security-Id" code="299" type="Unsigned32" mandatoryFlag="false" />
	<AVP_Def name="Multi-Round-Time-Out" code="272" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Origin-Host" code="264" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Origin-Realm" code="296" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Origin-State-Id" code="278" type="Unsigned32" mandatoryFlag="false" />
	<AVP_Def name="Product-Name" code="269" type="UTF8String" mandatoryFlag="false" />
	<AVP_Def name="Proxy-Host" code="280" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Proxy-Info" code="284" type="Grouped" mandatoryFlag="true" />
	<AVP_Def name="Proxy-State" code="33" type="OctetString" mandatoryFlag="true" />
	<AVP_Def name="Redirect-Host" code="292" type="DiameterURI" mandatoryFlag="true" />
	<AVP_Def name="Redirect-Host-Usage" code="261" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="DONT_CACHE" />
		<EnumValue value="1" comment="ALL_SESSION" />
		<EnumValue value="2" comment="ALL_REALM" />
		<EnumValue value="3" comment="REALM_AND_APPLICATION" />
		<EnumValue value="4" comment="ALL_APPLICATION" />
		<EnumValue value="5" comment="ALL_HOST" />
		<EnumValue value="6" comment="ALL_USER" />
	</AVP_Def>
	<AVP_Def name="Redirect-Max-Cache-Time" code="262" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Result-Code" code="268" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="1001" comment="DIAMETER_MULTI_ROUND_AUTH" />
		<EnumValue value="2001" comment="DIAMETER_SUCCESS" />
		<EnumValue value="2002" comment="DIAMETER_LIMITED_SUCCESS" />
		<EnumValue value="3001" comment="DIAMETER_COMMAND_UNSUPPORTED" />
		<EnumValue value="3002" comment="DIAMETER_UNABLE_TO_DELIVER" />
		<EnumValue value="3003" comment="DIAMETER_REALM_NOT_SERVED" />
		<EnumValue value="3004" comment="DIAMETER_TOO_BUSY" />
		<EnumValue value="3005" comment="DIAMETER_LOOP_DETECTED" />
		<EnumValue value="3006" comment="DIAMETER_REDIRECT_INDICATION" />
		<EnumValue value="3007" comment="DIAMETER_APPLICATION_UNSUPPORTED" />
		<EnumValue value="3008" comment="DIAMETER_INVALID_HDR_BITS" />
		<EnumValue value="3009" comment="DIAMETER_INVALID_AVP_BITS" />
		<EnumValue value="3010" comment="DIAMETER_UNKNOWN_PEER" />
		<EnumValue value="4001" comment="DIAMETER_AUTHENTICATION_REJECTED" />
		<EnumValue value="4002" comment="DIAMETER_OUT_OF_SPACE" />
		<EnumValue value="4003" comment="DIAMETER_ELECTION_LOST" />
		<EnumValue value="4005" comment="DIAMETER_ERROR_MIP_REPLY_FAILURE" />
		<EnumValue value="4006" comment="DIAMETER_ERROR_HA_NOT_AVAILABLE" />
		<EnumValue value="4007" comment="DIAMETER_ERROR_BAD_KEY" />
		<EnumValue value="4008" comment="DIAMETER_ERROR_MIP_FILTER_NOT_SUPPORTED" />
		<EnumValue value="4010" comment="DIAMETER_END_USER_SERVICE_DENIED" />
		<EnumValue value="4011" comment="DIAMETER_CREDIT_CONTROL_NOT_APPLICABLE" />
		<EnumValue value="4012" comment="DIAMETER_CREDIT_LIMIT_REACHED" />
		<EnumValue value="5001" comment="DIAMETER_AVP_UNSUPPORTED" />
		<EnumValue value="5002" comment="DIAMETER_UNKNOWN_SESSION_ID" />
		<EnumValue value="5003" comment="DIAMETER_AUTHORIZATION_REJECTED" />
		<EnumValue value="5004" comment="DIAMETER_INVALID_AVP_VALUE" />
		<EnumValue value="5005" comment="DIAMETER_MISSING_AVP" />
		<EnumValue value="5006" comment="DIAMETER_RESOURCES_EXCEEDED" />
		<EnumValue value="5007" comment="DIAMETER_CONTRADICTING_AVPS" />
		<EnumValue value="5008" comment="DIAMETER_AVP_NOT_ALLOWED" />
		<EnumValue value="5009" comment="DIAMETER_AVP_OCCURS_TOO_MANY_TIMES" />
		<EnumValue value="5010" comment="DIAMETER_NO_COMMON_APPLICATION" />
		<EnumValue value="5011" comment="DIAMETER_UNSUPPORTED_VERSION" />
		<EnumValue value="5012" comment="DIAMETER_UNABLE_TO_COMPLY" />
		<EnumValue value="5013" comment="DIAMETER_INVALID_BIT_IN_HEADER" />
		<EnumValue value="5014" comment="DIAMETER_INVALID_AVP_LENGTH" />
		<EnumValue value="5015" comment="DIAMETER_INVALID_MESSAGE_LENGTH" />
		<EnumValue value="5016" comment="DIAMETER_INVALID_AVP_BIT_COMBO" />
		<EnumValue value="5017" comment="DIAMETER_NO_COMMON_SECURITY" />
		<EnumValue value="5024" comment="DIAMETER_ERROR_NO_FOREIGN_HA_SERVICE" />
		<EnumValue value="5025" comment="DIAMETER_ERROR_END_TO_END_MIP_KEY_ENCRYPTION" />
		<EnumValue value="5030" comment="DIAMETER_USER_UNKNOWN" />
		<EnumValue value="5031" comment="DIAMETER_RATING_FAILED" />
	</AVP_Def>
	<AVP_Def name="Re-Auth-Request-Type" code="285" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="AUTHORIZE_ONLY" />
		<EnumValue value="1" comment="AUTHORIZE_AUTHENTICATE" />
	</AVP_Def>
	<AVP_Def name="Route-Record" code="282" type="DiameterIdentity" mandatoryFlag="true" />
	<AVP_Def name="Session-Id" code="263" type="UTF8String" mandatoryFlag="true" />
	<AVP_Def name="Session-Timeout" code="27" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Session-Binding" code="270" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Session-Server-Failover" code="271" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="0" comment="REFUSE_SERVICE" />
		<EnumValue value="1" comment="TRY_AGAIN" />
		<EnumValue value="2" comment="ALLOW_SERVICE" />
		<EnumValue value="3" comment="TRY_AGAIN_ALLOW_SERVICE" />
	</AVP_Def>
	<AVP_Def name="Supported-Vendor-Id" code="265" type="Unsigned32" mandatoryFlag="true" />
	<AVP_Def name="Termination-Cause" code="295" type="Enumerated" mandatoryFlag="true">
		<EnumValue value="1" comment="DIAMETER_LOGOUT" />
		<EnumValue value="2" comment="DIAMETER_SERVICE_NOT_PROVIDED" />
