=== S-YOU/trace-samples/opt_ffs/schema/netflowFlowset.xsd
<!--
XML Schema for Diameter base protocol addon.
The following schema validates the XML syntax that defines the Diameter AVP's.

Author: Henrik Pettersson <henrik.a.pettersson@ericsson.com>
Updated: Anders Olander <anders.olander@ericsson.com>
Copyright Ericsson AB, Sweden 2005
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- Top Tag -->
	
	<xs:element name="RequestData" type="RequestData_Type">		
	</xs:element>
	
	<xs:complexType name="RequestData_Type">
		<xs:choice>
			<xs:element name="TemplateFlowset" type="TemplateFlowset_type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="DataFlowsets" type="DataFlowsets_Type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OptionsTemplateFlowset" type="OptionsTemplateFlowset_type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OptionsDataFlowsets" type="OptionsDataFlowsets_type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Packet" type="Packet_type" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>		
	
	<xs:complexType name="TemplateFlowset_type">
		<xs:sequence>
			<xs:element name="Template" type="Template_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
		
	<!-- The AVP Tag Definition type. -->
	<xs:complexType name="Template_type">
		<xs:sequence>
			<xs:element name="Field" type="Field_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="templateId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
	</xs:complexType>
	
	<!-- The AVP Tag Definition type. -->
	<xs:complexType name="DataFlowsets_Type">
		<xs:sequence>
			<xs:element name="DataFlowset" type="DataFlowset_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="DataFlowset_type">
		<xs:sequence>
			<xs:element name="Field" type="Field_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="templateId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
	</xs:complexType>
	
	
	<xs:complexType name="OptionsTemplateFlowset_type">	
		<xs:sequence>
			<xs:element name="OptionsTemplate" type="OptionsTemplate_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
		
	<!-- The AVP Tag Definition type. -->
	<xs:complexType name="OptionsTemplate_type">
		<xs:sequence>
			<xs:element name="Scope" type="Scope_type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Field" type="Field_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="templateId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
	</xs:complexType>
	
	
	<!-- The AVP Tag Definition type. -->
	<xs:complexType name="OptionsDataFlowsets_type">
		<xs:sequence>
			<xs:element name="OptionsDataFlowset" type="OptionsDataFlowset_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="OptionsDataFlowset_type">
		<xs:sequence>
			<xs:element name="Scope" type="Data_Scope_type"  minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Field" type="Field_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="templateId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Field_type">		
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="length" type="xs:integer" use="optional"></xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Scope_type">		
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="length" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	
	
	<xs:complexType name="Data_Scope_type">		
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="Packet_type">	
		<xs:sequence>
			<xs:element name="Data" type="Data_type"  minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"></xs:attribute>
		<xs:attribute name="sourceId" type="xs:nonNegativeInteger" use="required"></xs:attribute>
	</xs:complexType>
		
	
	<xs:complexType name="Data_type">		
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="id" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== S-YOU/trace-samples/opt_ffs/config/netflow/TemplateFlowset.xml
<?xml version="1.0" encoding="UTF-8"?>
<RequestData  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="schema/netflowFlowset.xsd">
<TemplateFlowset>
	<Template id="1" templateId="256">
		<Field id="1" length="4" />
		<Field id="2" length="4" />
		<Field id="3" length="4"/>
		<Field id="4"/>
		<Field id="5"/>
		<Field id="12"/>
		<Field id="15"/>
		<Field id="34"/>
	</Template>
	<Template id="2" templateId="257">
		<Field id="1" length="4" />
		<Field id="2" length="4" />
		<Field id="3" length="4"/>
		<Field id="4"/>
		<Field id="6"/>
		<Field id="27"/>
		<Field id="28"/>
		<Field id="62"/>
	</Template>
	<Template id="3" templateId="258">
		<Field id="70"  />
		<Field id="71"  />
		<Field id="56" />
		<Field id="57"/>
		<Field id="7"/>
		<Field id="8"/>
		<Field id="32"/>
		<Field id="33"/>
	</Template>
	<Template id="4" templateId="259">
		<Field id="14" length="2" />
		<Field id="16" length="4" />
	</Template>
</TemplateFlowset>
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/netflow/DataFlowset.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="schema/netflowFlowset.xsd">
	<DataFlowsets>
		<DataFlowset id="1" templateId="1">		
			<Field id="1"  value="100" />
			<Field id="2"  value="50" />
			<Field id="3"  value="3" />
			<Field id="4"  value="34" />
			<Field id="5"  value="2" />
			<Field id="12" value="33.89.67.100" />
			<Field id="15" value ="127.23.44.55" />
			<Field id="34" value="60"/>
		</DataFlowset>
		<DataFlowset id="2" templateId="2">
			<Field id="1"   value="180" />
			<Field id="2"   value="45" />
			<Field id="3"   value="66"/>
			<Field id="4"   value="48"/>
			<Field id="6"   value="78"/>
			<Field id="27"  value="7890:1200:ABCD:EF34:99:0:0:1"/>
			<Field id="28"  value="10:19:10:33:45:56:1900:850"/>
			<Field id="62"  value="100:149:150:3883:445:526:1900:821"/>
		</DataFlowset>
		<DataFlowset id="3" templateId="3">
			<Field id="70"   value="83" />
			<Field id="71"   value="12228" />
			<Field id="56"   value="5.9.78.90.56.120"/>
			<Field id="57"   value="01:23:45:67:89:255"/>
			<Field id="7"    value="7777"/>
			<Field id="8"    value="90.90.77.56"/>
			<Field id="32"   value="4"/>
			<Field id="33"   value="9"/>
		</DataFlowset>
		<DataFlowset id="4" templateId="4">
			<Field id="14"   value="67" length="2"/>
			<Field id="16"   value="90" length="2"/>
			<Field id="80"   value="900" />
		</DataFlowset>
		<DataFlowset id="5" templateId="4">
			<Field id="14"  value="898"  length="2"/>
			<Field id="16"   value="4" length="4"/>
			<Field id="80"   value="955600" />
		</DataFlowset>
		<DataFlowset id="6" templateId="4">
			<Field id="14"   value="666"  length="2"/>
			<Field id="16"   value="1" length="2"/>
			<Field id="80"   value="1900" />
		</DataFlowset>
	</DataFlowsets>
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/netflow/Packet.xml
<?xml version="1.0" encoding="utf-8"?>
<RequestData   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="schema/netflowFlowset.xsd">
	<Packet id="1" sourceId="12345">		
		<Data name="Template" 			id="1"/>
		<Data name="Template" 			id="2"/>
		<Data name="DataFlowset" 		id="1"/>
		<Data name="DataFlowset" 		id="2"/>
		<Data name="DataFlowset"  		id="3"/>
		<Data name="Template" 			id="4"/>
		<Data name="Template" 			id="3"/>
	</Packet>
	<Packet id="2"  sourceId="123456">			
		<Data name="DataFlowset" 		id="1"/>
		<Data name="DataFlowset" 		id="2"/>
		<Data name="DataFlowset"  		id="3"/>
	</Packet>
	<Packet id="3"  sourceId="123645">	
		<Data name="OptionsTemplate" 	id="1"/>
		<Data name="Template" 			id="2"/>
		<Data name="OptionsDataFlowset" id="1"/>
		<Data name="DataFlowset" 		id="2"/>
		<Data name="DataFlowset"  		id="3"/>
		<Data name="Template" 			id="4"/>
		<Data name="Template" 			id="3"/>
	</Packet>
	<Packet id="4"  sourceId="612345">	
		<Data name="OptionsTemplate" 	id="1"/>	
		<Data name="OptionsTemplate" 	id="2"/>	
		<Data name="OptionsTemplate" 	id="3"/>	
		<Data name="OptionsTemplate" 	id="4"/>
	</Packet>
	<Packet id="5"  sourceId="123845">	
		<Data name="OptionsTemplate" 	id="1"/>
		<Data name="OptionsTemplate" 	id="2"/>
		<Data name="OptionsDataFlowset" id="1"/>
		<Data name="OptionsDataFlowset" id="1"/>
		<Data name="OptionsDataFlowset" id="1"/>
	</Packet>	
</RequestData>

=== S-YOU/trace-samples/opt_ffs/config/netflow/OptionsTemplateFlowset.xml
<?xml version="1.0" encoding="UTF-8"?>
<RequestData  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="schema/netflowFlowset.xsd">
<OptionsTemplateFlowset>
	<OptionsTemplate id="1" templateId="356">
		<Scope id="1" length="2" />
		<Scope id="2" length="2" />
		<Scope id="3" length="2" />
		<Field id="1" length="4" />
		<Field id="2" length="4" />
		<Field id="3" length="4"/>
		<Field id="4"/>
		<Field id="5"/>
		<Field id="12"/>
		<Field id="15"/>
		<Field id="34"/>
	</OptionsTemplate>
	<OptionsTemplate id="2" templateId="357">
		<Scope id="1" length="2" />
		<Scope id="2" length="2" />
		<Field id="1" length="4" />
		<Field id="2" length="4" />
		<Field id="3" length="4"/>
		<Field id="4"/>
		<Field id="6"/>
		<Field id="27"/>
		<Field id="28"/>
		<Field id="62"/>
	</OptionsTemplate>
	<OptionsTemplate id="3" templateId="358">
		<Scope id="3" length="2" />
		<Scope id="4" length="4" />
		<Field id="70"  />
		<Field id="71"  />
		<Field id="56" />
		<Field id="57"/>
		<Field id="7"/>
		<Field id="8"/>
		<Field id="32"/>
		<Field id="33"/>
	</OptionsTemplate>
	<OptionsTemplate id="4" templateId="359">
		<Field id="14" length="2" />
		<Field id="16" length="4" />
	</OptionsTemplate>
</OptionsTemplateFlowset>
</RequestData>
